//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/core/com/appnativa/rare/viewer/aFormViewer.java
//
//  Created by decoteaud on 12/8/15.
//

#ifndef _RAREaFormViewer_H_
#define _RAREaFormViewer_H_

@class JavaIoWriter;
@class JavaUtilHashMap;
@class RAREActionEvent;
@class RAREEventListenerList;
@class RARESPOTLink;
@class RARESPOTViewer;
@class RAREUTJSONWriter;
@protocol JavaUtilMap;
@protocol RAREiActionListener;
@protocol RAREiContainer;
@protocol RAREiFunctionCallback;

#import "JreEmulation.h"
#include "com/appnativa/rare/net/ActionLink.h"
#include "com/appnativa/rare/viewer/GroupBoxViewer.h"

@interface RAREaFormViewer : RAREGroupBoxViewer {
 @public
  RAREActionLink *formLink_;
  RAREEventListenerList *listenerList_;
  BOOL retainInitialFieldValues_;
  id<JavaUtilMap> submitAttributes_;
}

- (id)init;
- (id)initWithRAREiContainer:(id<RAREiContainer>)parent;
- (void)addActionListenerWithRAREiActionListener:(id<RAREiActionListener>)l;
- (void)configureWithRARESPOTViewer:(RARESPOTViewer *)vcfg;
- (JavaUtilHashMap *)getHTTPValuesHash;
- (void)removeActionListenerWithRAREiActionListener:(id<RAREiActionListener>)l;
- (void)submit;
- (void)submitFormWithRAREiFunctionCallback:(id<RAREiFunctionCallback>)cb;
- (void)writeHTTPContentWithBoolean:(BOOL)first
                   withJavaIoWriter:(JavaIoWriter *)writer
                       withNSString:(NSString *)boundary;
- (void)writeHTTPContentWithBoolean:(BOOL)first
                   withJavaIoWriter:(JavaIoWriter *)writer
                       withNSString:(NSString *)boundary
                    withJavaUtilMap:(id<JavaUtilMap>)attributes;
- (BOOL)writeHTTPValueWithBoolean:(BOOL)first
                 withJavaIoWriter:(JavaIoWriter *)writer;
- (BOOL)writeHTTPValueWithBoolean:(BOOL)first
                 withJavaIoWriter:(JavaIoWriter *)writer
                  withJavaUtilMap:(id<JavaUtilMap>)attributes;
- (void)writeJSONValueWithRAREUTJSONWriter:(RAREUTJSONWriter *)writer;
- (void)writeJSONValueWithRAREUTJSONWriter:(RAREUTJSONWriter *)writer
                           withJavaUtilMap:(id<JavaUtilMap>)attributes;
- (void)setSubmittAttributeWithNSString:(NSString *)name
                                 withId:(id)value;
- (void)setSubmittAttributesWithJavaUtilMap:(id<JavaUtilMap>)attributes;
- (id)getAttributeWithNSString:(NSString *)key;
- (RAREActionLink *)getFormLink;
- (id)getSubmittAttributeWithNSString:(NSString *)name;
- (BOOL)isRetainInitialWidgetValues;
- (void)clearConfigurationWithBoolean:(BOOL)dispose;
- (RAREActionLink *)createActionLinkWithRARESPOTLink:(RARESPOTLink *)link;
- (void)copyAllFieldsTo:(RAREaFormViewer *)other;
@end

J2OBJC_FIELD_SETTER(RAREaFormViewer, formLink_, RAREActionLink *)
J2OBJC_FIELD_SETTER(RAREaFormViewer, listenerList_, RAREEventListenerList *)
J2OBJC_FIELD_SETTER(RAREaFormViewer, submitAttributes_, id<JavaUtilMap>)

typedef RAREaFormViewer ComAppnativaRareViewerAFormViewer;

@interface RAREaFormViewer_FormLink : RAREActionLink {
 @public
  RAREaFormViewer *this$0_;
  BOOL dataWritten_;
}

- (id)initWithRAREaFormViewer:(RAREaFormViewer *)outer$
             withRARESPOTLink:(RARESPOTLink *)link;
- (void)actionPerformedWithRAREActionEvent:(RAREActionEvent *)e;
- (void)close;
- (void)writeFormData;
- (void)closeOutput;
- (void)copyAllFieldsTo:(RAREaFormViewer_FormLink *)other;
@end

J2OBJC_FIELD_SETTER(RAREaFormViewer_FormLink, this$0_, RAREaFormViewer *)

#endif // _RAREaFormViewer_H_
