//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/core/com/appnativa/rare/ui/event/ExpansionEvent.java
//
//  Created by decoteaud on 3/11/16.
//

#ifndef _RAREExpansionEvent_H_
#define _RAREExpansionEvent_H_

@class RAREExpansionEvent_TypeEnum;

#import "JreEmulation.h"
#include "com/appnativa/rare/ui/event/EventBase.h"
#include "java/lang/Enum.h"

@interface RAREExpansionEvent : RAREEventBase {
 @public
  RAREExpansionEvent_TypeEnum *type_;
  __weak id eventItem_;
}

- (id)initWithId:(id)source
withRAREExpansionEvent_TypeEnum:(RAREExpansionEvent_TypeEnum *)type;
- (id)initWithId:(id)source
withRAREExpansionEvent_TypeEnum:(RAREExpansionEvent_TypeEnum *)type
          withId:(id)item;
- (RAREExpansionEvent_TypeEnum *)getEventType;
- (void)reject;
- (NSString *)description;
- (void)setItemWithId:(id)item;
- (id)getItem;
- (BOOL)isTypeWithRAREExpansionEvent_TypeEnum:(RAREExpansionEvent_TypeEnum *)type;
- (void)copyAllFieldsTo:(RAREExpansionEvent *)other;
@end

J2OBJC_FIELD_SETTER(RAREExpansionEvent, type_, RAREExpansionEvent_TypeEnum *)

typedef RAREExpansionEvent ComAppnativaRareUiEventExpansionEvent;

typedef enum {
  RAREExpansionEvent_Type_WILL_EXPAND = 0,
  RAREExpansionEvent_Type_WILL_COLLAPSE = 1,
  RAREExpansionEvent_Type_HAS_EXPANDED = 2,
  RAREExpansionEvent_Type_HAS_COLLAPSED = 3,
} RAREExpansionEvent_Type;

@interface RAREExpansionEvent_TypeEnum : JavaLangEnum < NSCopying > {
}
+ (RAREExpansionEvent_TypeEnum *)WILL_EXPAND;
+ (RAREExpansionEvent_TypeEnum *)WILL_COLLAPSE;
+ (RAREExpansionEvent_TypeEnum *)HAS_EXPANDED;
+ (RAREExpansionEvent_TypeEnum *)HAS_COLLAPSED;
+ (IOSObjectArray *)values;
+ (RAREExpansionEvent_TypeEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;
- (id)initWithNSString:(NSString *)__name withInt:(int)__ordinal;
@end

#endif // _RAREExpansionEvent_H_
