//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/apple/com/appnativa/rare/ui/event/MouseEventEx.java
//
//  Created by decoteaud on 12/8/15.
//

#ifndef _RAREMouseEventEx_H_
#define _RAREMouseEventEx_H_

#import "JreEmulation.h"
#include "com/appnativa/rare/ui/event/MouseEvent.h"

@interface RAREMouseEventEx : RAREMouseEvent {
}

- (id)initWithId:(id)source
          withId:(id)me
         withInt:(int)modifiers;
- (id)initWithId:(id)source
          withId:(id)me1
         withInt:(int)modifiers
          withId:(id)me2
       withFloat:(float)x
       withFloat:(float)y;
- (id)initWithId:(id)source
          withId:(id)me;
@end

typedef RAREMouseEventEx ComAppnativaRareUiEventMouseEventEx;

#endif // _RAREMouseEventEx_H_
