//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc/guava/sources/com/google/common/collect/AbstractMapEntry.java
//
//  Created by tball on 11/23/13.
//

#import "JreEmulation.h"

#if !ComGoogleCommonCollectAbstractMapEntry_RESTRICT
#define ComGoogleCommonCollectAbstractMapEntry_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectAbstractMapEntry_RESTRICT

#if !defined (_ComGoogleCommonCollectAbstractMapEntry_) && (ComGoogleCommonCollectAbstractMapEntry_INCLUDE_ALL || ComGoogleCommonCollectAbstractMapEntry_INCLUDE)
#define _ComGoogleCommonCollectAbstractMapEntry_

#define JavaUtilMap_RESTRICT 1
#define JavaUtilMap_Entry_INCLUDE 1
#include "java/util/Map.h"

@interface ComGoogleCommonCollectAbstractMapEntry : NSObject < JavaUtilMap_Entry > {
}

- (id)getKey;
- (id)getValue;
- (id)setValueWithId:(id)value;
- (BOOL)isEqual:(id)object;
- (NSUInteger)hash;
- (NSString *)description;
- (id)init;
@end
#endif
