//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc/guava/sources/com/google/common/collect/DiscreteDomains.java
//
//  Created by tball on 11/23/13.
//

#import "JreEmulation.h"

#if !ComGoogleCommonCollectDiscreteDomains_RESTRICT
#define ComGoogleCommonCollectDiscreteDomains_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectDiscreteDomains_RESTRICT

#if !defined (_ComGoogleCommonCollectDiscreteDomains_) && (ComGoogleCommonCollectDiscreteDomains_INCLUDE_ALL || ComGoogleCommonCollectDiscreteDomains_INCLUDE)
#define _ComGoogleCommonCollectDiscreteDomains_

@class ComGoogleCommonCollectDiscreteDomain;

@interface ComGoogleCommonCollectDiscreteDomains : NSObject {
}

- (id)init;
+ (ComGoogleCommonCollectDiscreteDomain *)integers;
+ (ComGoogleCommonCollectDiscreteDomain *)longs;
@end
#endif
