//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/core/com/appnativa/rare/ui/tree/iExpansionHandler.java
//
//  Created by decoteaud on 9/15/15.
//

#ifndef _RAREiExpansionHandler_H_
#define _RAREiExpansionHandler_H_

@protocol RAREiTree;
@protocol RAREiTreeItem;

#import "JreEmulation.h"

@protocol RAREiExpansionHandler < NSObject, JavaObject >
- (int)toggleExpansionWithRAREiTree:(id<RAREiTree>)tree
                  withRAREiTreeItem:(id<RAREiTreeItem>)item
                            withInt:(int)listModelIndex;
@end

#define ComAppnativaRareUiTreeIExpansionHandler RAREiExpansionHandler

#endif // _RAREiExpansionHandler_H_
