//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/core/com/appnativa/rare/ui/border/aUIIconBorder.java
//
//  Created by decoteaud on 3/11/16.
//

#ifndef _RAREaUIIconBorder_H_
#define _RAREaUIIconBorder_H_

@class RARENinePatch;
@class RARERenderTypeEnum;
@class RAREUIImage;
@class RAREUIImagePainter;
@class RAREUIInsets;
@protocol RAREiPlatformBorder;
@protocol RAREiPlatformGraphics;
@protocol RAREiPlatformIcon;
@protocol RAREiPlatformPainter;

#import "JreEmulation.h"
#include "com/appnativa/rare/ui/border/aUIPlatformBorder.h"

@interface RAREaUIIconBorder : RAREaUIPlatformBorder {
 @public
  BOOL leftRight_;
  id<RAREiPlatformIcon> bottomIcon_;
  RAREUIImagePainter *bottomPainter_;
  RARERenderTypeEnum *bottomRt_;
  RAREUIInsets *insets_;
  float left_, right_, top_, bottom_;
  id<RAREiPlatformIcon> leftIcon_;
  float leftPad_;
  RAREUIImagePainter *leftPainter_;
  RARERenderTypeEnum *leftRt_;
  RARENinePatch *ninePatch_;
  id<RAREiPlatformBorder> overLayBorder_;
  RAREUIImage *pattern_;
  id<RAREiPlatformIcon> rightIcon_;
  RAREUIImagePainter *rightPainter_;
  RARERenderTypeEnum *rightRt_;
  id<RAREiPlatformIcon> topIcon_;
  float topPad_;
  RAREUIImagePainter *topPainter_;
  RARERenderTypeEnum *topRt_;
}

- (id)initWithRAREUIInsets:(RAREUIInsets *)insets;
- (id)initWithInt:(int)top
          withInt:(int)right
          withInt:(int)bottom
          withInt:(int)left;
- (id)clone;
- (void)paintWithRAREiPlatformGraphics:(id<RAREiPlatformGraphics>)g
                             withFloat:(float)x
                             withFloat:(float)y
                             withFloat:(float)width
                             withFloat:(float)height
                           withBoolean:(BOOL)end;
- (void)setBottomIconWithRAREiPlatformIcon:(id<RAREiPlatformIcon>)icon;
- (void)setIconsWithRAREiPlatformIcon:(id<RAREiPlatformIcon>)top
                withRAREiPlatformIcon:(id<RAREiPlatformIcon>)right
                withRAREiPlatformIcon:(id<RAREiPlatformIcon>)bottom
                withRAREiPlatformIcon:(id<RAREiPlatformIcon>)left;
- (void)setInsetsWithRAREUIInsets:(RAREUIInsets *)insets;
- (void)setInsetsWithInt:(int)top
                 withInt:(int)right
                 withInt:(int)bottom
                 withInt:(int)left;
- (void)setLeftIconWithRAREiPlatformIcon:(id<RAREiPlatformIcon>)icon;
- (void)setLeftPadWithInt:(int)leftPad;
- (void)setNinePatchWithRARENinePatch:(RARENinePatch *)ninePatch;
- (void)setOverLayBorderWithRAREiPlatformBorder:(id<RAREiPlatformBorder>)overLayBorder;
- (void)setPatternWithRAREUIImage:(RAREUIImage *)image;
- (void)setPrecedenceWithBoolean:(BOOL)leftRight;
- (void)setRenderInfoWithRARERenderTypeEnum:(RARERenderTypeEnum *)top
                                    withInt:(int)topop
                     withRARERenderTypeEnum:(RARERenderTypeEnum *)left
                                    withInt:(int)leftop
                     withRARERenderTypeEnum:(RARERenderTypeEnum *)bottom
                                    withInt:(int)bottomop
                     withRARERenderTypeEnum:(RARERenderTypeEnum *)right
                                    withInt:(int)rightop;
- (void)setRightIconWithRAREiPlatformIcon:(id<RAREiPlatformIcon>)icon;
- (void)setTopIconWithRAREiPlatformIcon:(id<RAREiPlatformIcon>)icon;
- (void)setTopPadWithInt:(int)topPad;
- (RAREUIInsets *)getBorderInsetsWithRAREUIInsets:(RAREUIInsets *)insets;
- (id<RAREiPlatformIcon>)getBottomIcon;
- (id<RAREiPlatformIcon>)getLeftIcon;
- (float)getLeftPad;
- (id<RAREiPlatformBorder>)getOverLayBorder;
- (id<RAREiPlatformIcon>)getRightIcon;
- (id<RAREiPlatformIcon>)getTopIcon;
- (float)getTopPad;
- (BOOL)isLeftRightPrecedence;
- (BOOL)isPaintLast;
- (RAREUIInsets *)addjustInsetsWithRAREUIInsets:(RAREUIInsets *)insets;
- (RAREUIImagePainter *)createImagePainterWithRAREiPlatformIcon:(id<RAREiPlatformIcon>)icon
                                         withRARERenderTypeEnum:(RARERenderTypeEnum *)rt
                                                        withInt:(int)alpha
                                         withRAREUIImagePainter:(RAREUIImagePainter *)ip;
- (void)paintIconWithRAREiPlatformIcon:(id<RAREiPlatformIcon>)icon
             withRAREiPlatformGraphics:(id<RAREiPlatformGraphics>)g
                             withFloat:(float)x
                             withFloat:(float)y;
- (void)paintPainterWithRAREiPlatformPainter:(id<RAREiPlatformPainter>)p
                   withRAREiPlatformGraphics:(id<RAREiPlatformGraphics>)g
                                   withFloat:(float)x
                                   withFloat:(float)y
                                   withFloat:(float)width
                                   withFloat:(float)height;
- (void)paintPatternWithRAREUIImage:(RAREUIImage *)image
          withRAREiPlatformGraphics:(id<RAREiPlatformGraphics>)g
                          withFloat:(float)x
                          withFloat:(float)y
                          withFloat:(float)width
                          withFloat:(float)height;
- (void)copyAllFieldsTo:(RAREaUIIconBorder *)other;
@end

J2OBJC_FIELD_SETTER(RAREaUIIconBorder, bottomIcon_, id<RAREiPlatformIcon>)
J2OBJC_FIELD_SETTER(RAREaUIIconBorder, bottomPainter_, RAREUIImagePainter *)
J2OBJC_FIELD_SETTER(RAREaUIIconBorder, bottomRt_, RARERenderTypeEnum *)
J2OBJC_FIELD_SETTER(RAREaUIIconBorder, insets_, RAREUIInsets *)
J2OBJC_FIELD_SETTER(RAREaUIIconBorder, leftIcon_, id<RAREiPlatformIcon>)
J2OBJC_FIELD_SETTER(RAREaUIIconBorder, leftPainter_, RAREUIImagePainter *)
J2OBJC_FIELD_SETTER(RAREaUIIconBorder, leftRt_, RARERenderTypeEnum *)
J2OBJC_FIELD_SETTER(RAREaUIIconBorder, ninePatch_, RARENinePatch *)
J2OBJC_FIELD_SETTER(RAREaUIIconBorder, overLayBorder_, id<RAREiPlatformBorder>)
J2OBJC_FIELD_SETTER(RAREaUIIconBorder, pattern_, RAREUIImage *)
J2OBJC_FIELD_SETTER(RAREaUIIconBorder, rightIcon_, id<RAREiPlatformIcon>)
J2OBJC_FIELD_SETTER(RAREaUIIconBorder, rightPainter_, RAREUIImagePainter *)
J2OBJC_FIELD_SETTER(RAREaUIIconBorder, rightRt_, RARERenderTypeEnum *)
J2OBJC_FIELD_SETTER(RAREaUIIconBorder, topIcon_, id<RAREiPlatformIcon>)
J2OBJC_FIELD_SETTER(RAREaUIIconBorder, topPainter_, RAREUIImagePainter *)
J2OBJC_FIELD_SETTER(RAREaUIIconBorder, topRt_, RARERenderTypeEnum *)

typedef RAREaUIIconBorder ComAppnativaRareUiBorderAUIIconBorder;

#endif // _RAREaUIIconBorder_H_
