//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/apple/com/appnativa/rare/ui/border/SharedLineBorder.java
//
//  Created by decoteaud on 9/15/15.
//

#ifndef _RARESharedLineBorder_H_
#define _RARESharedLineBorder_H_

@class RAREUIColor;

#import "JreEmulation.h"
#include "com/appnativa/rare/ui/border/aSharedLineBorder.h"

@interface RARESharedLineBorder : RAREaSharedLineBorder {
}

- (id)initWithRAREUIColor:(RAREUIColor *)color;
- (id)initWithRAREUIColor:(RAREUIColor *)color
                withFloat:(float)thickness;
- (id)initWithRAREUIColor:(RAREUIColor *)color
                withFloat:(float)thickness
              withBoolean:(BOOL)roundedCorners;
- (id)initWithRAREUIColor:(RAREUIColor *)color
                withFloat:(float)thickness
                  withInt:(int)arc;
- (id)initWithRAREUIColor:(RAREUIColor *)color
                withFloat:(float)thickness
                  withInt:(int)arcWidth
                  withInt:(int)arcHeight;
- (BOOL)canUseMainLayer;
@end

typedef RARESharedLineBorder ComAppnativaRareUiBorderSharedLineBorder;

#endif // _RARESharedLineBorder_H_
