//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/apple-tabpane/com/appnativa/rare/ui/tabpane/TabPaneLayout.java
//
//  Created by decoteaud on 12/8/15.
//

#include "com/appnativa/rare/platform/apple/ui/view/FrameView.h"
#include "com/appnativa/rare/platform/apple/ui/view/View.h"
#include "com/appnativa/rare/ui/RenderType.h"
#include "com/appnativa/rare/ui/iParentComponent.h"
#include "com/appnativa/rare/ui/tabpane/TabPaneLayout.h"
#include "com/appnativa/rare/ui/tabpane/aTabPaneLayout.h"
#include "com/appnativa/rare/ui/tabpane/aTabStripComponent.h"

@implementation RARETabPaneLayout

- (id)initWithRAREaTabPaneLayout_iContentManager:(id<RAREaTabPaneLayout_iContentManager>)cm {
  return [super initWithRAREaTabPaneLayout_iContentManager:cm];
}

- (void)configureRotationWithInt:(int)degrees {
  [((RAREView *) nil_chk([((RAREaTabStripComponent *) nil_chk(tabStrip_)) getView])) setRotationWithInt:degrees];
}

- (void)setContentRenderTypeWithRARERenderTypeEnum:(RARERenderTypeEnum *)type {
  RAREFrameView *fv = (RAREFrameView *) check_class_cast([((id<RAREiParentComponent>) nil_chk(contentArea_)) getView], [RAREFrameView class]);
  [((RAREFrameView *) nil_chk(fv)) setViewRenderTypeWithRARERenderTypeEnum:type];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "configureRotationWithInt:", NULL, "V", 0x4, NULL },
    { "setContentRenderTypeWithRARERenderTypeEnum:", NULL, "V", 0x4, NULL },
  };
  static J2ObjcClassInfo _RARETabPaneLayout = { "TabPaneLayout", "com.appnativa.rare.ui.tabpane", NULL, 0x1, 2, methods, 0, NULL, 0, NULL};
  return &_RARETabPaneLayout;
}

@end
