//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc/jsr305/build_result/java/javax/annotation/Nonnegative.java
//
//  Created by tball on 11/23/13.
//

#ifndef _JavaxAnnotationNonnegative_H_
#define _JavaxAnnotationNonnegative_H_

@class JavaxAnnotationMetaWhenEnum;

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"
#include "javax/annotation/meta/TypeQualifierValidator.h"

@protocol JavaxAnnotationNonnegative < JavaLangAnnotationAnnotation >

@property (readonly) JavaxAnnotationMetaWhenEnum *when;

@end

@interface JavaxAnnotationNonnegative : NSObject < JavaxAnnotationNonnegative > {
 @private
  JavaxAnnotationMetaWhenEnum *when;
}

- (id)initWithWhen:(JavaxAnnotationMetaWhenEnum *)when_;

+ (JavaxAnnotationMetaWhenEnum *)whenDefault;

@end

@interface JavaxAnnotationNonnegative_Checker : NSObject < JavaxAnnotationMetaTypeQualifierValidator > {
}

- (JavaxAnnotationMetaWhenEnum *)forConstantValueWithId:(id<JavaxAnnotationNonnegative>)annotation
                                                 withId:(id)v;
- (id)init;
@end

#endif // _JavaxAnnotationNonnegative_H_
