//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/apple/com/appnativa/rare/platform/apple/ui/view/SectionIndex.java
//
//  Created by decoteaud on 7/29/15.
//

#include "IOSIntArray.h"
#include "IOSObjectArray.h"
#include "com/appnativa/rare/platform/apple/ui/view/SectionIndex.h"
#include "com/appnativa/rare/ui/RenderableDataItem.h"
#include "com/appnativa/rare/ui/painter/PaintBucket.h"

@implementation RARESectionIndex

- (id)init {
  if (self = [super init]) {
    indexPath_ = [IOSIntArray arrayWithLength:2];
  }
  return self;
}

- (id)initWithNSStringArray:(IOSObjectArray *)titles
               withIntArray:(IOSIntArray *)position
               withIntArray:(IOSIntArray *)length
 withRARERenderableDataItem:(RARERenderableDataItem *)prototype {
  if (self = [super init]) {
    indexPath_ = [IOSIntArray arrayWithLength:2];
    self->titles_ = titles;
    self->position_ = position;
    self->length_ = length;
    self->indextitles_ = titles;
    sectionPrototype_ = prototype;
  }
  return self;
}

- (int)getSectionCount {
  return (int) [((IOSIntArray *) nil_chk(self->position_)) count];
}

- (NSString *)getTitleTextWithInt:(int)section {
  return IOSObjectArray_Get(nil_chk(titles_), section);
}

- (NSString *)getIndexTextWithInt:(int)section {
  return IOSObjectArray_Get(nil_chk(indextitles_), section);
}

- (int)getFlatIndexWithInt:(int)section
                   withInt:(int)position {
  return IOSIntArray_Get(nil_chk(self->position_), section) + position;
}

- (int)getSizeWithInt:(int)section {
  return IOSIntArray_Get(nil_chk(self->length_), section);
}

- (IOSIntArray *)getIndexPathForFlatPositionWithInt:(int)position {
  IOSIntArray *p = self->position_;
  IOSIntArray *l = self->length_;
  int len = (int) [((IOSIntArray *) nil_chk(p)) count];
  IOSIntArray *ip = indexPath_;
  int index = 0;
  for (int i = 0; i < len; i++) {
    index += IOSIntArray_Get(nil_chk(l), i);
    if (index > position) {
      index -= IOSIntArray_Get(l, i);
      (*IOSIntArray_GetRef(nil_chk(ip), 0)) = i;
      (*IOSIntArray_GetRef(ip, 1)) = position - index;
      break;
    }
  }
  return ip;
}

- (void)copyAllFieldsTo:(RARESectionIndex *)other {
  [super copyAllFieldsTo:other];
  other->indexPath_ = indexPath_;
  other->indextitles_ = indextitles_;
  other->length_ = length_;
  other->painter_ = painter_;
  other->position_ = position_;
  other->sectionPrototype_ = sectionPrototype_;
  other->titles_ = titles_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "getTitleTextWithInt:", NULL, "LNSString", 0x1, NULL },
    { "getIndexTextWithInt:", NULL, "LNSString", 0x1, NULL },
    { "getIndexPathForFlatPositionWithInt:", NULL, "LIOSIntArray", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "indextitles_", NULL, 0x1, "LIOSObjectArray" },
    { "painter_", NULL, 0x1, "LRAREPaintBucket" },
    { "position_", NULL, 0x1, "LIOSIntArray" },
    { "length_", NULL, 0x1, "LIOSIntArray" },
    { "titles_", NULL, 0x1, "LIOSObjectArray" },
    { "sectionPrototype_", NULL, 0x1, "LRARERenderableDataItem" },
  };
  static J2ObjcClassInfo _RARESectionIndex = { "SectionIndex", "com.appnativa.rare.platform.apple.ui.view", NULL, 0x1, 3, methods, 6, fields, 0, NULL};
  return &_RARESectionIndex;
}

@end
