//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc/testing/mockito/build_result/java/org/mockito/internal/stubbing/defaultanswers/ReturnsMoreEmptyValues.java
//
//  Created by tball on 11/23/13.
//

#ifndef _OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues_H_
#define _OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues_H_

@class IOSClass;
@protocol OrgMockitoInvocationInvocationOnMock;

#import "JreEmulation.h"
#include "java/io/Serializable.h"
#include "org/mockito/stubbing/Answer.h"

#define OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues_serialVersionUID -2816745041482698471

@interface OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues : NSObject < OrgMockitoStubbingAnswer, JavaIoSerializable > {
 @public
  id<OrgMockitoStubbingAnswer> delegate_;
}

- (id)answerWithOrgMockitoInvocationInvocationOnMock:(id<OrgMockitoInvocationInvocationOnMock>)invocation;
- (id)returnValueForWithIOSClass:(IOSClass *)type;
- (id)init;
- (void)copyAllFieldsTo:(OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues *)other;
@end

J2OBJC_FIELD_SETTER(OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues, delegate_, id<OrgMockitoStubbingAnswer>)

#endif // _OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues_H_
