//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/apple/com/appnativa/rare/ui/iPlatformImagePanel.java
//
//  Created by decoteaud on 7/29/15.
//

#ifndef _RAREiPlatformImagePanel_H_
#define _RAREiPlatformImagePanel_H_

#import "JreEmulation.h"
#include "com/appnativa/rare/ui/iImagePanel.h"

@protocol RAREiPlatformImagePanel < RAREiImagePanel, NSObject, JavaObject >
@end

#define ComAppnativaRareUiIPlatformImagePanel RAREiPlatformImagePanel

#endif // _RAREiPlatformImagePanel_H_
