//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/core/com/appnativa/rare/ui/iScrollerSupport.java
//
//  Created by decoteaud on 12/8/15.
//

#ifndef _RAREiScrollerSupport_H_
#define _RAREiScrollerSupport_H_

@class RAREUIPoint;
@class RAREUIScrollingEdgePainter;

#import "JreEmulation.h"

@protocol RAREiScrollerSupport < NSObject, JavaObject >
- (BOOL)isScrolling;
- (BOOL)isAtLeftEdge;
- (BOOL)isAtRightEdge;
- (BOOL)isAtTopEdge;
- (BOOL)isAtBottomEdge;
- (RAREUIPoint *)getContentOffset;
- (void)setScrollingEdgePainterWithRAREUIScrollingEdgePainter:(RAREUIScrollingEdgePainter *)painter;
- (RAREUIScrollingEdgePainter *)getScrollingEdgePainter;
- (void)scrollToBottomEdge;
- (void)scrollToLeftEdge;
- (void)scrollToRightEdge;
- (void)scrollToTopEdge;
- (void)moveUpDownWithBoolean:(BOOL)up
                  withBoolean:(BOOL)block;
- (void)moveLeftRightWithBoolean:(BOOL)left
                     withBoolean:(BOOL)block;
- (void)setContentOffsetWithFloat:(float)x
                        withFloat:(float)y;
@end

#define ComAppnativaRareUiIScrollerSupport RAREiScrollerSupport

#endif // _RAREiScrollerSupport_H_
