//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/apple/com/appnativa/rare/ui/LinearPanel.java
//
//  Created by decoteaud on 3/11/16.
//

#ifndef _RARELinearPanel_H_
#define _RARELinearPanel_H_

@class IOSObjectArray;
@class RARECellConstraints;
@class RAREFormLayout;
@protocol RAREiPlatformComponent;
@protocol RAREiWidget;

#import "JreEmulation.h"
#include "com/appnativa/rare/ui/aLinearPanel.h"

@interface RARELinearPanel : RAREaLinearPanel {
}

- (id)initWithBoolean:(BOOL)horizontal;
- (id)initWithRAREiWidget:(id<RAREiWidget>)context
              withBoolean:(BOOL)horizontal;
- (id)initWithRAREiWidget:(id<RAREiWidget>)context
              withBoolean:(BOOL)horizontal
             withNSString:(NSString *)rspec
             withNSString:(NSString *)cspec;
- (void)setCellPaintersWithRAREiPlatformPainterArray:(IOSObjectArray *)painters;
- (RARECellConstraints *)getCellConstraintsWithRAREiPlatformComponent:(id<RAREiPlatformComponent>)component;
- (RAREFormLayout *)getFormLayout;
- (void)updateFormLayout;
@end

typedef RARELinearPanel ComAppnativaRareUiLinearPanel;

#endif // _RARELinearPanel_H_
