//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc/testing/mockito/build_result/java/org/mockito/exceptions/misusing/FriendlyReminderException.java
//
//  Created by tball on 11/23/13.
//

#ifndef _OrgMockitoExceptionsMisusingFriendlyReminderException_H_
#define _OrgMockitoExceptionsMisusingFriendlyReminderException_H_

#import "JreEmulation.h"
#include "org/mockito/exceptions/base/MockitoException.h"

#define OrgMockitoExceptionsMisusingFriendlyReminderException_serialVersionUID 1

@interface OrgMockitoExceptionsMisusingFriendlyReminderException : OrgMockitoExceptionsBaseMockitoException {
}

- (id)initWithNSString:(NSString *)message;
@end

#endif // _OrgMockitoExceptionsMisusingFriendlyReminderException_H_
