//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/core/com/appnativa/rare/ui/aBorderPanel.java
//
//  Created by decoteaud on 9/15/15.
//

#include "com/appnativa/rare/ui/Container.h"
#include "com/appnativa/rare/ui/Location.h"
#include "com/appnativa/rare/ui/UIDimension.h"
#include "com/appnativa/rare/ui/UIInsets.h"
#include "com/appnativa/rare/ui/aBorderPanel.h"
#include "com/appnativa/rare/ui/iPlatformComponent.h"
#include "com/appnativa/rare/ui/layout/BorderLayout.h"
#include "com/jgoodies/forms/layout/CellConstraints.h"

@implementation RAREaBorderPanel

- (id)init {
  return [super init];
}

- (id)initWithId:(id)view {
  return [super initWithId:view];
}

- (void)setBottomViewWithRAREiPlatformComponent:(id<RAREiPlatformComponent>)c {
  if (c != nil) {
    if ([self getBottomView] == c) {
      return;
    }
    [self removeWithRAREiPlatformComponent:c];
  }
  [self addWithRAREiPlatformComponent:c withId:[RARELocationEnum BOTTOM]];
}

- (void)setCenterViewWithRAREiPlatformComponent:(id<RAREiPlatformComponent>)c {
  if (c != nil) {
    if ([self getCenterView] == c) {
      return;
    }
    [self removeWithRAREiPlatformComponent:c];
  }
  [self addWithRAREiPlatformComponent:c withId:[RARELocationEnum CENTER]];
}

- (void)setHorizontalWithBoolean:(BOOL)horizontal {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

- (void)setLeftViewWithRAREiPlatformComponent:(id<RAREiPlatformComponent>)c {
  if (c != nil) {
    if ([self getLeftView] == c) {
      return;
    }
    [self removeWithRAREiPlatformComponent:c];
  }
  [self addWithRAREiPlatformComponent:c withId:[RARELocationEnum LEFT]];
}

- (void)setRightViewWithRAREiPlatformComponent:(id<RAREiPlatformComponent>)c {
  if (c != nil) {
    if ([self getRightView] == c) {
      return;
    }
    [self removeWithRAREiPlatformComponent:c];
  }
  [self addWithRAREiPlatformComponent:c withId:[RARELocationEnum RIGHT]];
}

- (void)setTopBottomPriorityWithBoolean:(BOOL)topBottomPriority {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

- (void)setTopViewWithRAREiPlatformComponent:(id<RAREiPlatformComponent>)c {
  if (c != nil) {
    if ([self getTopView] == c) {
      return;
    }
    [self removeWithRAREiPlatformComponent:c];
  }
  [self addWithRAREiPlatformComponent:c withId:[RARELocationEnum TOP]];
}

- (id<RAREiPlatformComponent>)getBottomView {
  return [self getComponentAtWithRARELocationEnum:[RARELocationEnum BOTTOM]];
}

- (RAREJGCellConstraints *)getCellConstraintsWithRAREiPlatformComponent:(id<RAREiPlatformComponent>)component {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<RAREiPlatformComponent>)getCenterView {
  return [self getComponentAtWithRARELocationEnum:[RARELocationEnum CENTER]];
}

- (id<RAREiPlatformComponent>)getLeftView {
  return [self getComponentAtWithRARELocationEnum:[RARELocationEnum LEFT]];
}

- (id<RAREiPlatformComponent>)getRightView {
  return [self getComponentAtWithRARELocationEnum:[RARELocationEnum RIGHT]];
}

- (id<RAREiPlatformComponent>)getTopView {
  return [self getComponentAtWithRARELocationEnum:[RARELocationEnum TOP]];
}

- (RARELOBorderLayout *)getBorderLayout {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<RAREiPlatformComponent>)getComponentAtWithRARELocationEnum:(RARELocationEnum *)location {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (RAREJGCellConstraints *)getConstraintsWithRARELocationEnum:(RARELocationEnum *)location {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (void)getMinimumSizeExWithRAREUIDimension:(RAREUIDimension *)size {
  [((RARELOBorderLayout *) nil_chk([self getBorderLayout])) invalidateMinimumCache];
  (void) [((RARELOBorderLayout *) nil_chk([self getBorderLayout])) getMinimumSizeWithRAREiParentComponent:self withRAREUIDimension:size];
  RAREUIInsets *in = margin_;
  if (margin_ != nil) {
    ((RAREUIDimension *) nil_chk(size))->width_ += ((RAREUIInsets *) nil_chk(in))->left_ + in->right_;
    size->height_ += in->top_ + in->bottom_;
  }
}

- (void)getPreferredSizeExWithRAREUIDimension:(RAREUIDimension *)size
                                    withFloat:(float)maxWidth {
  (void) [((RARELOBorderLayout *) nil_chk([self getBorderLayout])) getPreferredSizeWithRAREiParentComponent:self withRAREUIDimension:size withFloat:maxWidth];
  RAREUIInsets *in = margin_;
  if (margin_ != nil) {
    ((RAREUIDimension *) nil_chk(size))->width_ += ((RAREUIInsets *) nil_chk(in))->left_ + in->right_;
    size->height_ += in->top_ + in->bottom_;
  }
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "setHorizontalWithBoolean:", NULL, "V", 0x401, NULL },
    { "setTopBottomPriorityWithBoolean:", NULL, "V", 0x401, NULL },
    { "getBottomView", NULL, "LRAREiPlatformComponent", 0x1, NULL },
    { "getCellConstraintsWithRAREiPlatformComponent:", NULL, "LRAREJGCellConstraints", 0x401, NULL },
    { "getCenterView", NULL, "LRAREiPlatformComponent", 0x1, NULL },
    { "getLeftView", NULL, "LRAREiPlatformComponent", 0x1, NULL },
    { "getRightView", NULL, "LRAREiPlatformComponent", 0x1, NULL },
    { "getTopView", NULL, "LRAREiPlatformComponent", 0x1, NULL },
    { "getBorderLayout", NULL, "LRARELOBorderLayout", 0x404, NULL },
    { "getComponentAtWithRARELocationEnum:", NULL, "LRAREiPlatformComponent", 0x404, NULL },
    { "getConstraintsWithRARELocationEnum:", NULL, "LRAREJGCellConstraints", 0x404, NULL },
    { "getMinimumSizeExWithRAREUIDimension:", NULL, "V", 0x4, NULL },
    { "getPreferredSizeExWithRAREUIDimension:withFloat:", NULL, "V", 0x4, NULL },
  };
  static J2ObjcClassInfo _RAREaBorderPanel = { "aBorderPanel", "com.appnativa.rare.ui", NULL, 0x401, 13, methods, 0, NULL, 0, NULL};
  return &_RAREaBorderPanel;
}

@end
