//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/core/com/appnativa/rare/ui/aFormsPanel.java
//
//  Created by decoteaud on 12/8/15.
//

#include "IOSBooleanArray.h"
#include "IOSIntArray.h"
#include "IOSObjectArray.h"
#include "com/appnativa/rare/ui/Container.h"
#include "com/appnativa/rare/ui/UIDimension.h"
#include "com/appnativa/rare/ui/UIPoint.h"
#include "com/appnativa/rare/ui/UIRectangle.h"
#include "com/appnativa/rare/ui/aComponent.h"
#include "com/appnativa/rare/ui/aFormsPanel.h"
#include "com/appnativa/rare/ui/iFormsPanel.h"
#include "com/appnativa/rare/ui/iPlatformComponent.h"
#include "com/jgoodies/forms/layout/CellConstraints.h"
#include "com/jgoodies/forms/layout/ColumnSpec.h"
#include "com/jgoodies/forms/layout/ConstantSize.h"
#include "com/jgoodies/forms/layout/FormLayout.h"
#include "com/jgoodies/forms/layout/FormSpec.h"
#include "com/jgoodies/forms/layout/RowSpec.h"
#include "com/jgoodies/forms/layout/Size.h"
#include "com/jgoodies/forms/layout/Sizes.h"
#include "java/lang/StringBuilder.h"

@implementation RAREaFormsPanel

static RAREJGRowSpec * RAREaFormsPanel_emptyRowSpec_;
static RAREJGColumnSpec * RAREaFormsPanel_emptyColumnSpec_;
static RAREJGRowSpec * RAREaFormsPanel_defaultRowSpec_;
static RAREJGColumnSpec * RAREaFormsPanel_defaultColumnSpec_;

+ (RAREJGRowSpec *)emptyRowSpec {
  return RAREaFormsPanel_emptyRowSpec_;
}

+ (void)setEmptyRowSpec:(RAREJGRowSpec *)emptyRowSpec {
  RAREaFormsPanel_emptyRowSpec_ = emptyRowSpec;
}

+ (RAREJGColumnSpec *)emptyColumnSpec {
  return RAREaFormsPanel_emptyColumnSpec_;
}

+ (void)setEmptyColumnSpec:(RAREJGColumnSpec *)emptyColumnSpec {
  RAREaFormsPanel_emptyColumnSpec_ = emptyColumnSpec;
}

+ (RAREJGRowSpec *)defaultRowSpec {
  return RAREaFormsPanel_defaultRowSpec_;
}

+ (void)setDefaultRowSpec:(RAREJGRowSpec *)defaultRowSpec {
  RAREaFormsPanel_defaultRowSpec_ = defaultRowSpec;
}

+ (RAREJGColumnSpec *)defaultColumnSpec {
  return RAREaFormsPanel_defaultColumnSpec_;
}

+ (void)setDefaultColumnSpec:(RAREJGColumnSpec *)defaultColumnSpec {
  RAREaFormsPanel_defaultColumnSpec_ = defaultColumnSpec;
}

- (id)init {
  return [super init];
}

- (id)initWithId:(id)view {
  return [super initWithId:view];
}

- (int)addColumnWithInt:(int)index
           withNSString:(NSString *)colspec {
  RAREJGFormLayout *l = [self getFormLayout];
  RAREJGColumnSpec *c = [RAREJGColumnSpec decodeWithNSString:(colspec == nil) ? @"FILL:DEFAULT:NONE" : colspec];
  if ((index < 0) || (index >= [((RAREJGFormLayout *) nil_chk(l)) getColumnCount])) {
    [((RAREJGFormLayout *) nil_chk(l)) appendColumnWithRAREJGColumnSpec:c];
    return [l getColumnCount] - 1;
  }
  else {
    [l insertColumnWithRAREiParentComponent:self withInt:index + 1 withRAREJGColumnSpec:c];
    return index;
  }
}

- (void)addColumnSpacingWithInt:(int)space {
  id<RAREJGSize> s = (space == 0) ? [RAREJGSizes ZERO] : [RAREJGSizes pixelWithInt:space];
  RAREJGColumnSpec *c = [[RAREJGColumnSpec alloc] initWithRAREJGFormSpec_DefaultAlignment:[RAREJGColumnSpec DEFAULT] withRAREJGSize:s withDouble:0];
  RAREJGFormLayout *l = [self getFormLayout];
  int len = [((RAREJGFormLayout *) nil_chk(l)) getColumnCount];
  for (int i = len; i > 1; i--) {
    [l insertColumnWithRAREiParentComponent:self withInt:i withRAREJGColumnSpec:c];
  }
}

- (void)addComponentWithRAREiPlatformComponent:(id<RAREiPlatformComponent>)comp
                                       withInt:(int)col
                                       withInt:(int)row {
  [self addComponentWithRAREiPlatformComponent:comp withInt:col withInt:row withInt:1 withInt:1];
}

- (void)addComponentWithRAREiPlatformComponent:(id<RAREiPlatformComponent>)comp
                                       withInt:(int)col
                                       withInt:(int)row
                                       withInt:(int)rowspan
                                       withInt:(int)colspan {
  [self ensureGridWithInt:col + 1 withInt:row + 1 withBoolean:NO withBoolean:NO withInt:0 withInt:0];
  [self addWithRAREiPlatformComponent:comp withId:[self createConstraintsWithInt:col withInt:row withInt:rowspan withInt:colspan]];
}

- (int)addRowWithInt:(int)index
        withNSString:(NSString *)rowspec {
  RAREJGFormLayout *l = [self getFormLayout];
  RAREJGRowSpec *r = [RAREJGRowSpec decodeWithNSString:(rowspec == nil) ? @"CENTER:DEFAULT:NONE" : rowspec];
  if ((index < 0) || (index >= [((RAREJGFormLayout *) nil_chk(l)) getRowCount])) {
    [((RAREJGFormLayout *) nil_chk(l)) appendRowWithRAREJGRowSpec:r];
    return [l getRowCount] - 1;
  }
  else {
    [l insertRowWithRAREiParentComponent:self withInt:index + 1 withRAREJGRowSpec:r];
    return index;
  }
}

- (void)addRowSpacingWithInt:(int)space {
  id<RAREJGSize> s = (space == 0) ? [RAREJGSizes ZERO] : [RAREJGSizes pixelWithInt:space];
  RAREJGRowSpec *r = [[RAREJGRowSpec alloc] initWithRAREJGFormSpec_DefaultAlignment:[RAREJGRowSpec DEFAULT] withRAREJGSize:s withDouble:0];
  RAREJGFormLayout *l = [self getFormLayout];
  int len = [((RAREJGFormLayout *) nil_chk(l)) getRowCount];
  for (int i = len; i > 1; i--) {
    [l insertRowWithRAREiParentComponent:self withInt:i withRAREJGRowSpec:r];
  }
}

- (void)addSpacerColumnWithInt:(int)space {
  id<RAREJGSize> s = (space == 0) ? [RAREJGSizes ZERO] : [RAREJGSizes pixelWithInt:space];
  RAREJGColumnSpec *c = [[RAREJGColumnSpec alloc] initWithRAREJGFormSpec_DefaultAlignment:[RAREJGColumnSpec DEFAULT] withRAREJGSize:s withDouble:0];
  RAREJGFormLayout *l = [self getFormLayout];
  [((RAREJGFormLayout *) nil_chk(l)) appendColumnWithRAREJGColumnSpec:c];
}

- (void)addSpacerRowWithInt:(int)space {
  RAREJGFormLayout *l = [self getFormLayout];
  id<RAREJGSize> s = (space == 0) ? [RAREJGSizes ZERO] : [RAREJGSizes pixelWithInt:space];
  RAREJGRowSpec *r = [[RAREJGRowSpec alloc] initWithRAREJGFormSpec_DefaultAlignment:[RAREJGRowSpec DEFAULT] withRAREJGSize:s withDouble:0];
  [((RAREJGFormLayout *) nil_chk(l)) appendRowWithRAREJGRowSpec:r];
}

- (void)addSpacingWithInt:(int)rowSpace
                  withInt:(int)columnSpace {
  [self addColumnSpacingWithInt:columnSpace];
  [self addRowSpacingWithInt:rowSpace];
}

- (RAREJGCellConstraints *)createConstraintsWithInt:(int)col
                                            withInt:(int)row
                                            withInt:(int)rowspan
                                            withInt:(int)colspan {
  row++;
  col++;
  return [[RAREJGCellConstraints alloc] initWithInt:col withInt:row withInt:colspan withInt:rowspan];
}

- (void)dispose {
  if (![self isDisposed]) {
    RAREJGFormLayout *l = [self getFormLayout];
    if (l != nil) {
      [l dispose];
    }
    [super dispose];
  }
}

- (void)ensureGridWithInt:(int)cols
                  withInt:(int)rows
                  withInt:(int)rspacing
                  withInt:(int)cspacing {
  [self ensureGridWithInt:cols withInt:rows withBoolean:NO withBoolean:NO withInt:rspacing withInt:cspacing];
}

- (void)fillEmptySpace {
  RAREJGFormLayout *l = [self getFormLayout];
  RAREJGFormLayout_LayoutInfo *info = [self getLayoutInfo];
  int len = [((RAREJGFormLayout *) nil_chk(l)) getRowCount];
  for (int i = 0; i < len; i++) {
    if (tableLayout_ && (i % 2 == 0)) {
      continue;
    }
    if ([RAREaFormsPanel isRowEmptyWithInt:i withRAREJGFormLayout_LayoutInfo:info]) {
      [l setRowSpecWithInt:i + 1 withRAREJGRowSpec:RAREaFormsPanel_emptyRowSpec_];
    }
  }
  len = [l getColumnCount];
  for (int i = 0; i < len; i++) {
    if (tableLayout_ && (i % 2 == 0)) {
      continue;
    }
    if ([RAREaFormsPanel isColumnEmptyWithInt:i withRAREJGFormLayout_LayoutInfo:info]) {
      [l setColumnSpecWithInt:i + 1 withRAREJGColumnSpec:RAREaFormsPanel_emptyColumnSpec_];
    }
  }
}

- (void)growColumnWithInt:(int)col {
  [((RAREJGFormLayout *) nil_chk([self getFormLayout])) setColumnSpecWithInt:col + 1 withRAREJGColumnSpec:[RAREJGColumnSpec decodeWithNSString:@"FILL:DEFAULT:GROW(1.0)"]];
}

- (void)growRowWithInt:(int)row {
  [((RAREJGFormLayout *) nil_chk([self getFormLayout])) setRowSpecWithInt:row + 1 withRAREJGRowSpec:[RAREJGRowSpec decodeWithNSString:@"CENTER:DEFAULT:GROW(1.0)"]];
}

- (void)removeWithRAREiPlatformComponent:(id<RAREiPlatformComponent>)c {
  [super removeWithRAREiPlatformComponent:c];
  if (c != nil) {
    RAREJGFormLayout *l = [self getFormLayout];
    if (l != nil) {
      [l removeLayoutComponentWithRAREiPlatformComponent:c];
    }
  }
}

- (void)removeColumnWithInt:(int)col {
  RAREJGFormLayout *l = [self getFormLayout];
  [((RAREJGFormLayout *) nil_chk(l)) removeColumnWithRAREiParentComponent:self withInt:col + 1];
}

- (void)removeRowWithInt:(int)row {
  RAREJGFormLayout *l = [self getFormLayout];
  [((RAREJGFormLayout *) nil_chk(l)) removeRowWithRAREiParentComponent:self withInt:row + 1];
}

- (void)setColumnGroupsWithIntArray2:(IOSObjectArray *)cg {
  [((RAREJGFormLayout *) nil_chk([self getFormLayout])) setColumnGroupsWithIntArray2:cg];
}

- (void)setColumnSpecWithInt:(int)col
                withNSString:(NSString *)spec {
  [((RAREJGFormLayout *) nil_chk([self getFormLayout])) setColumnSpecWithInt:col + 1 withRAREJGColumnSpec:[RAREJGColumnSpec decodeWithNSString:spec]];
}

- (void)setLayoutWithNSString:(NSString *)cstr
                 withNSString:(NSString *)rstr {
  [((RAREJGFormLayout *) nil_chk([self getFormLayout])) setLayoutWithNSString:cstr withNSString:rstr];
}

- (void)setRowGroupsWithIntArray2:(IOSObjectArray *)rg {
  [((RAREJGFormLayout *) nil_chk([self getFormLayout])) setRowGroupsWithIntArray2:rg];
}

- (void)setRowSpecWithInt:(int)row
             withNSString:(NSString *)spec {
  [((RAREJGFormLayout *) nil_chk([self getFormLayout])) setRowSpecWithInt:row + 1 withRAREJGRowSpec:[RAREJGRowSpec decodeWithNSString:spec]];
}

- (void)setSpacerRowWithInt:(int)row
                    withInt:(int)space {
  RAREJGFormLayout *l = [self getFormLayout];
  RAREJGRowSpec *r = [RAREJGRowSpec decodeWithNSString:[NSString stringWithFormat:@"CENTER:%dPX:NONE", space]];
  [((RAREJGFormLayout *) nil_chk(l)) setRowSpecWithInt:row + 1 withRAREJGRowSpec:r];
}

- (void)setTableLayoutWithBoolean:(BOOL)tableLayout {
  self->tableLayout_ = tableLayout;
}

- (RAREJGCellConstraints *)getCellConstraintsWithRAREUIPoint:(RAREUIPoint *)p {
  if (p == nil) {
    return nil;
  }
  RAREJGFormLayout_LayoutInfo *info = [self getLayoutInfo];
  IOSIntArray *cols = ((RAREJGFormLayout_LayoutInfo *) nil_chk(info))->columnOrigins_;
  IOSIntArray *rows = info->rowOrigins_;
  int w = [info getWidth];
  int h = [info getHeight];
  int cw;
  int rh;
  RAREUIRectangle *r = [[RAREUIRectangle alloc] init];
  for (int y = 0; y < (int) [((IOSIntArray *) nil_chk(rows)) count]; y++) {
    for (int x = 0; x < (int) [((IOSIntArray *) nil_chk(cols)) count]; x++) {
      if (x + 1 == (int) [cols count]) {
        cw = w - IOSIntArray_Get(cols, x) + 1;
      }
      else {
        cw = IOSIntArray_Get(cols, x + 1) - IOSIntArray_Get(cols, x) + 1;
      }
      if (y + 1 == (int) [rows count]) {
        rh = h - IOSIntArray_Get(rows, y) + 1;
      }
      else {
        rh = IOSIntArray_Get(rows, y + 1) - IOSIntArray_Get(rows, y) + 1;
      }
      [r setBoundsWithFloat:IOSIntArray_Get(cols, x) withFloat:IOSIntArray_Get(rows, y) withFloat:cw withFloat:rh];
      if ([r containsWithRAREUIPoint:p]) {
        return [[RAREJGCellConstraints alloc] initWithInt:x + 1 withInt:y + 1];
      }
    }
  }
  return nil;
}

- (int)getColumnWithRAREiPlatformComponent:(id<RAREiPlatformComponent>)component {
  RAREJGCellConstraints *cc = [self getCellConstraintsWithRAREiPlatformComponent:component];
  return (cc == nil) ? -1 : cc->gridX_ - 1;
}

- (int)getColumnWithRAREUIPoint:(RAREUIPoint *)p {
  RAREJGCellConstraints *cc = [self getCellConstraintsWithRAREUIPoint:p];
  return (cc == nil) ? -1 : cc->gridX_ - 1;
}

- (int)getColumnCount {
  return [((RAREJGFormLayout *) nil_chk([self getFormLayout])) getColumnCount];
}

- (NSString *)getColumns {
  return [self getColumnsWithInt:-1];
}

- (NSString *)getColumnsWithInt:(int)skip {
  return [RAREaFormsPanel getColumnsWithRAREJGFormLayout:[self getFormLayout] withInt:skip];
}

+ (NSString *)getColumnsWithRAREJGFormLayout:(RAREJGFormLayout *)l
                                     withInt:(int)skip {
  JavaLangStringBuilder *sb = [[JavaLangStringBuilder alloc] initWithInt:80];
  int len = [((RAREJGFormLayout *) nil_chk(l)) getColumnCount];
  for (int i = 0; i < len; i++) {
    if (i != skip) {
      (void) [((JavaLangStringBuilder *) nil_chk([sb appendWithNSString:[((RAREJGColumnSpec *) nil_chk([l getColumnSpecWithInt:i + 1])) encodeEx]])) appendWithChar:','];
    }
  }
  [sb setLengthWithInt:[sb sequenceLength] - 1];
  return [sb description];
}

- (id<RAREiPlatformComponent>)getComponent {
  return self;
}

- (id)getComponentConstraintsWithRAREiPlatformComponent:(id<RAREiPlatformComponent>)component {
  return [self getCellConstraintsWithRAREiPlatformComponent:component];
}

- (int)getFormHeight {
  return [((RAREJGFormLayout_LayoutInfo *) nil_chk([self getLayoutInfo])) getHeight];
}

- (RAREJGFormLayout *)getFormLayout {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (int)getFormWidth {
  return [((RAREJGFormLayout_LayoutInfo *) nil_chk([self getLayoutInfo])) getWidth];
}

- (id<RAREiPlatformComponent>)getGridComponentAtWithInt:(int)col
                                                withInt:(int)row {
  return [((RAREJGFormLayout *) nil_chk([self getFormLayout])) getComponentAtWithRAREiParentComponent:self withInt:col withInt:row];
}

- (int)getRowWithRAREiPlatformComponent:(id<RAREiPlatformComponent>)component {
  RAREJGCellConstraints *cc = [self getCellConstraintsWithRAREiPlatformComponent:component];
  return (cc == nil) ? -1 : cc->gridY_ - 1;
}

- (int)getRowWithRAREUIPoint:(RAREUIPoint *)p {
  RAREJGCellConstraints *cc = [self getCellConstraintsWithRAREUIPoint:p];
  return (cc == nil) ? -1 : cc->gridY_ - 1;
}

- (int)getRowCount {
  return [((RAREJGFormLayout *) nil_chk([self getFormLayout])) getRowCount];
}

- (NSString *)getRows {
  return [self getRowsWithInt:-1];
}

- (NSString *)getRowsWithInt:(int)skip {
  return [RAREaFormsPanel getRowsWithRAREJGFormLayout:[self getFormLayout] withInt:skip];
}

+ (NSString *)getRowsWithRAREJGFormLayout:(RAREJGFormLayout *)l
                                  withInt:(int)skip {
  JavaLangStringBuilder *sb = [[JavaLangStringBuilder alloc] initWithInt:80];
  int len = [((RAREJGFormLayout *) nil_chk(l)) getRowCount];
  for (int i = 0; i < len; i++) {
    if (i != skip) {
      (void) [((JavaLangStringBuilder *) nil_chk([sb appendWithNSString:[((RAREJGRowSpec *) nil_chk([l getRowSpecWithInt:i + 1])) encodeEx]])) appendWithChar:','];
    }
  }
  [sb setLengthWithInt:[sb sequenceLength] - 1];
  return [sb description];
}

+ (BOOL)isColumnEmptyWithInt:(int)column
withRAREJGFormLayout_LayoutInfo:(RAREJGFormLayout_LayoutInfo *)info {
  return (IOSIntArray_Get(nil_chk(((RAREJGFormLayout_LayoutInfo *) nil_chk(info))->columnOrigins_), column + 1) - IOSIntArray_Get(info->columnOrigins_, column)) < 2;
}

- (IOSBooleanArray *)isColumnRowComponentsHiddenWithInt:(int)col
                                                withInt:(int)row {
  return [((RAREJGFormLayout *) nil_chk([self getFormLayout])) isColumnRowComponentsHiddenWithRAREiParentComponent:self withInt:col withInt:row];
}

+ (BOOL)isRowEmptyWithInt:(int)row
withRAREJGFormLayout_LayoutInfo:(RAREJGFormLayout_LayoutInfo *)info {
  return (IOSIntArray_Get(nil_chk(((RAREJGFormLayout_LayoutInfo *) nil_chk(info))->rowOrigins_), row + 1) - IOSIntArray_Get(info->rowOrigins_, row)) < 2;
}

- (BOOL)isTableLayout {
  return tableLayout_;
}

- (void)ensureGridWithInt:(int)cols
                  withInt:(int)rows
              withBoolean:(BOOL)growRow
              withBoolean:(BOOL)growColumn
                  withInt:(int)rspacing
                  withInt:(int)cspacing {
  RAREJGFormLayout *l = [self getFormLayout];
  rows -= [((RAREJGFormLayout *) nil_chk(l)) getRowCount];
  cols -= [l getColumnCount];
  if (rows > 0) {
    RAREJGRowSpec *r;
    if (growRow) {
      r = [RAREJGRowSpec decodeWithNSString:@"CENTER:DEFAULT:GROW(1.0)"];
    }
    else {
      r = [RAREJGRowSpec decodeWithNSString:@"CENTER:DEFAULT:NONE"];
    }
    for (int i = 0; i < rows; i++) {
      if (rspacing > 0) {
        [self addSpacerRowWithInt:rspacing];
      }
      [l appendRowWithRAREJGRowSpec:r];
    }
  }
  if (cols > 0) {
    RAREJGColumnSpec *c;
    if (growColumn) {
      c = [RAREJGColumnSpec decodeWithNSString:@"FILL:DEFAULT:GROW(1.0)"];
    }
    else {
      c = [RAREJGColumnSpec decodeWithNSString:@"FILL:DEFAULT:NONE"];
    }
    for (int i = 0; i < cols; i++) {
      if (cspacing > 0) {
        [self addSpacerColumnWithInt:cspacing];
      }
      [l appendColumnWithRAREJGColumnSpec:c];
    }
  }
}

- (RAREJGFormLayout_LayoutInfo *)getLayoutInfo {
  return [((RAREJGFormLayout *) nil_chk([self getFormLayout])) getLayoutInfoWithRAREiParentComponent:self];
}

- (void)getMinimumSizeExWithRAREUIDimension:(RAREUIDimension *)size
                                  withFloat:(float)maxWidth {
  (void) [((RAREJGFormLayout *) nil_chk([self getFormLayout])) getMinimumSizeWithRAREiParentComponent:self withRAREUIDimension:size withFloat:maxWidth];
}

- (void)getPreferredSizeExWithRAREUIDimension:(RAREUIDimension *)size
                                    withFloat:(float)maxWidth {
  (void) [((RAREJGFormLayout *) nil_chk([self getFormLayout])) getPreferredSizeWithRAREiParentComponent:self withRAREUIDimension:size withFloat:maxWidth];
}

- (RAREJGCellConstraints *)getCellConstraintsWithRAREiPlatformComponent:(id<RAREiPlatformComponent>)param0 {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (void)setCellPaintersWithRAREiPlatformPainterArray:(IOSObjectArray *)param0 {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

+ (void)initialize {
  if (self == [RAREaFormsPanel class]) {
    RAREaFormsPanel_emptyRowSpec_ = [RAREJGRowSpec decodeWithNSString:@"14dlu"];
    RAREaFormsPanel_emptyColumnSpec_ = [RAREJGColumnSpec decodeWithNSString:@"14dlu"];
    RAREaFormsPanel_defaultRowSpec_ = [RAREJGRowSpec decodeWithNSString:@"d"];
    RAREaFormsPanel_defaultColumnSpec_ = [RAREJGColumnSpec decodeWithNSString:@"d"];
  }
}

- (void)copyAllFieldsTo:(RAREaFormsPanel *)other {
  [super copyAllFieldsTo:other];
  other->tableLayout_ = tableLayout_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "createConstraintsWithInt:withInt:withInt:withInt:", NULL, "LRAREJGCellConstraints", 0x1, NULL },
    { "getCellConstraintsWithRAREUIPoint:", NULL, "LRAREJGCellConstraints", 0x1, NULL },
    { "getColumns", NULL, "LNSString", 0x1, NULL },
    { "getColumnsWithInt:", NULL, "LNSString", 0x1, NULL },
    { "getColumnsWithRAREJGFormLayout:withInt:", NULL, "LNSString", 0x9, NULL },
    { "getComponent", NULL, "LRAREiPlatformComponent", 0x1, NULL },
    { "getComponentConstraintsWithRAREiPlatformComponent:", NULL, "LNSObject", 0x1, NULL },
    { "getFormLayout", NULL, "LRAREJGFormLayout", 0x401, NULL },
    { "getGridComponentAtWithInt:withInt:", NULL, "LRAREiPlatformComponent", 0x1, NULL },
    { "getRows", NULL, "LNSString", 0x1, NULL },
    { "getRowsWithInt:", NULL, "LNSString", 0x1, NULL },
    { "getRowsWithRAREJGFormLayout:withInt:", NULL, "LNSString", 0x9, NULL },
    { "isColumnEmptyWithInt:withRAREJGFormLayout_LayoutInfo:", NULL, "Z", 0x9, NULL },
    { "isColumnRowComponentsHiddenWithInt:withInt:", NULL, "LIOSBooleanArray", 0x1, NULL },
    { "isRowEmptyWithInt:withRAREJGFormLayout_LayoutInfo:", NULL, "Z", 0x9, NULL },
    { "isTableLayout", NULL, "Z", 0x1, NULL },
    { "ensureGridWithInt:withInt:withBoolean:withBoolean:withInt:withInt:", NULL, "V", 0x4, NULL },
    { "getLayoutInfo", NULL, "LRAREJGFormLayout_LayoutInfo", 0x4, NULL },
    { "getMinimumSizeExWithRAREUIDimension:withFloat:", NULL, "V", 0x4, NULL },
    { "getPreferredSizeExWithRAREUIDimension:withFloat:", NULL, "V", 0x4, NULL },
    { "getCellConstraintsWithRAREiPlatformComponent:", NULL, "LRAREJGCellConstraints", 0x401, NULL },
    { "setCellPaintersWithRAREiPlatformPainterArray:", NULL, "V", 0x401, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "emptyRowSpec_", NULL, 0x9, "LRAREJGRowSpec" },
    { "emptyColumnSpec_", NULL, 0x9, "LRAREJGColumnSpec" },
    { "defaultRowSpec_", NULL, 0x9, "LRAREJGRowSpec" },
    { "defaultColumnSpec_", NULL, 0x9, "LRAREJGColumnSpec" },
    { "tableLayout_", NULL, 0x4, "Z" },
  };
  static J2ObjcClassInfo _RAREaFormsPanel = { "aFormsPanel", "com.appnativa.rare.ui", NULL, 0x401, 22, methods, 5, fields, 0, NULL};
  return &_RAREaFormsPanel;
}

@end
