//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/core/com/appnativa/rare/ui/iObservableImage.java
//
//  Created by decoteaud on 3/11/16.
//

#include "com/appnativa/rare/ui/iImageObserver.h"
#include "com/appnativa/rare/ui/iObservableImage.h"


@interface RAREiObservableImage : NSObject
@end

@implementation RAREiObservableImage

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "isImageLoadedWithRAREiImageObserver:", NULL, "Z", 0x401, NULL },
  };
  static J2ObjcClassInfo _RAREiObservableImage = { "iObservableImage", "com.appnativa.rare.ui", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_RAREiObservableImage;
}

@end
