//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/apple-table_and_tree/com/appnativa/rare/ui/table/TreeTableView.java
//
//  Created by decoteaud on 9/15/15.
//

#ifndef _RARETreeTableView_H_
#define _RARETreeTableView_H_

@class RARERenderableDataItem;
@protocol RAREiTreeItem;

#import "JreEmulation.h"
#include "com/appnativa/rare/platform/apple/ui/view/TreeView.h"

@interface RARETreeTableView : RARETreeView {
 @public
  BOOL parentItemsSelectable_;
}

- (id)init;
- (void)setParentItemsSelectableWithBoolean:(BOOL)parentItemsSelectable;
- (BOOL)isParentItemsSelectable;
- (void)createHeader;
+ (id)createTreeTableProxy;
- (void)updateRenderInsetsForCheckBoxWithFloat:(float)left
                                     withFloat:(float)right;
- (BOOL)isSelectableWithInt:(int)row
 withRARERenderableDataItem:(RARERenderableDataItem *)item
          withRAREiTreeItem:(id<RAREiTreeItem>)ti;
- (BOOL)isTable;
- (void)copyAllFieldsTo:(RARETreeTableView *)other;
@end

typedef RARETreeTableView ComAppnativaRareUiTableTreeTableView;

#endif // _RARETreeTableView_H_
