//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../spot/src/com/appnativa/spot/SPOTHelper.java
//
//  Created by decoteaud on 9/15/15.
//

#ifndef _SPOTHelper_H_
#define _SPOTHelper_H_

@class IOSClass;
@class IOSObjectArray;
@class JavaLangReflectField;
@class JavaUtilHashMap;
@protocol JavaUtilMap;
@protocol RAREUTiPackageHelper;
@protocol iSPOTElement;

#import "JreEmulation.h"

@interface SPOTHelper : NSObject {
}

+ (IOSObjectArray *)_setRefType;
+ (void)set_setRefType:(IOSObjectArray *)_setRefType;
+ (JavaUtilHashMap *)_toSpotName;
+ (JavaUtilHashMap *)_fromSpotName;
+ (id<RAREUTiPackageHelper>)packageHelper;
+ (void)setPackageHelper:(id<RAREUTiPackageHelper>)packageHelper;
- (id)init;
+ (IOSClass *)createDefinedByClassWithISPOTElement:(id<iSPOTElement>)parent
                                      withNSString:(NSString *)definedBy;
+ (IOSClass *)loadClassWithNSString:(NSString *)name;
+ (IOSClass *)getFieldClassWithJavaLangReflectField:(JavaLangReflectField *)field;
+ (NSString *)getPackageNameWithIOSClass:(IOSClass *)cls;
+ (NSString *)createDefinedByStringWithISPOTElement:(id<iSPOTElement>)parent
                                       withNSString:(NSString *)definedby;
+ (id<iSPOTElement>)elementFromNameWithJavaUtilMap:(id<JavaUtilMap>)refClassMap
                                  withISPOTElement:(id<iSPOTElement>)parent
                                      withNSString:(NSString *)name;
+ (void)setReferenceVariableWithISPOTElement:(id<iSPOTElement>)parent
                                withNSString:(NSString *)name
                            withISPOTElement:(id<iSPOTElement>)element;
+ (NSString *)getRelativeClassNameWithISPOTElement:(id<iSPOTElement>)obj;
+ (NSString *)resolveClassNameWithISPOTElement:(id<iSPOTElement>)obj
                                  withNSString:(NSString *)type;
+ (NSString *)getRelativeShortNameWithIOSClass:(IOSClass *)caller
                                  withIOSClass:(IOSClass *)cls;
+ (id<RAREUTiPackageHelper>)getPackageHelper;
+ (void)setPackageHelperWithRAREUTiPackageHelper:(id<RAREUTiPackageHelper>)helper;
@end

typedef SPOTHelper ComAppnativaSpotSPOTHelper;

#endif // _SPOTHelper_H_
