//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/core/com/appnativa/rare/net/HTTPException.java
//
//  Created by decoteaud on 12/8/15.
//

#include "IOSByteArray.h"
#include "com/appnativa/rare/net/HTTPException.h"
#include "com/appnativa/util/ISO88591Helper.h"
#include "java/io/IOException.h"
#include "java/io/InputStream.h"
#include "java/lang/Exception.h"
#include "java/lang/StringBuilder.h"
#include "java/lang/Throwable.h"
#include "java/net/HttpURLConnection.h"
#include "java/net/URL.h"

@implementation RAREHTTPException

- (id)initWithJavaNetHttpURLConnection:(JavaNetHttpURLConnection *)conn {
  if (self = [super init]) {
    statusBody_ = nil;
    statusCode_ = -1;
    cleanedUp_ = NO;
    statusMessage_ = nil;
    httpConn_ = conn;
    url_ = [((JavaNetURL *) nil_chk([((JavaNetHttpURLConnection *) nil_chk(conn)) getURL])) description];
  }
  return self;
}

- (id)initWithNSString:(NSString *)msg
withJavaNetHttpURLConnection:(JavaNetHttpURLConnection *)conn {
  if (self = [super initWithNSString:msg]) {
    statusBody_ = nil;
    statusCode_ = -1;
    cleanedUp_ = NO;
    statusMessage_ = nil;
    httpConn_ = conn;
    url_ = [((JavaNetURL *) nil_chk([((JavaNetHttpURLConnection *) nil_chk(conn)) getURL])) description];
  }
  return self;
}

- (void)cleanup {
  (void) [self getMessageBody];
}

- (JavaNetHttpURLConnection *)geConnection {
  return httpConn_;
}

- (NSString *)description {
  return [NSString stringWithFormat:@"%@\x0d\n%d %@\x0d\n%@", url_, [self getStatusCode], [self getStatus], [self getMessageBody]];
}

- (NSString *)getMessageBody {
  if (statusBody_ == nil) {
    IOSByteArray *buf = nil;
    JavaLangStringBuilder *sb = [[JavaLangStringBuilder alloc] init];
    if (!cleanedUp_) {
      int ret;
      JavaNetHttpURLConnection *hc = httpConn_;
      RAREUTISO88591Helper *iso = [RAREUTISO88591Helper getInstance];
      @try {
        JavaIoInputStream *es = [((JavaNetHttpURLConnection *) nil_chk(hc)) getErrorStream];
        if (es != nil) {
          buf = [IOSByteArray arrayWithLength:256];
          while ((ret = [es readWithByteArray:buf]) > 0) {
            (void) [sb appendWithNSString:[((RAREUTISO88591Helper *) nil_chk(iso)) getStringWithByteArray:buf withInt:0 withInt:ret]];
          }
          [es close];
        }
      }
      @catch (JavaLangException *ignored) {
      }
      cleanedUp_ = YES;
      statusBody_ = [sb description];
    }
  }
  return statusBody_;
}

- (NSString *)getMessage {
  return [self getStatusEx];
}

- (NSString *)getStatus {
  if (statusMessage_ == nil) {
    @try {
      statusMessage_ = [((JavaNetHttpURLConnection *) nil_chk(httpConn_)) getResponseMessage];
    }
    @catch (JavaIoIOException *ex) {
      statusMessage_ = @"";
    }
    @try {
      if ([super getMessage] != nil) {
        statusMessage_ = [NSString stringWithFormat:@"%@\x0d\n%@", [super getMessage], statusMessage_];
      }
    }
    @catch (JavaLangException *ex) {
      statusMessage_ = @"";
    }
  }
  return statusMessage_;
}

- (int)getStatusCode {
  if (statusCode_ == -1) {
    @try {
      statusCode_ = [((JavaNetHttpURLConnection *) nil_chk(httpConn_)) getResponseCode];
    }
    @catch (JavaIoIOException *ex) {
      statusCode_ = JavaNetHttpURLConnection_HTTP_BAD_REQUEST;
    }
  }
  return statusCode_;
}

- (NSString *)getStatusEx {
  return [NSString stringWithFormat:@"%@ (%@)", [self getStatus], url_];
}

- (void)dealloc {
  @try {
    (void) [self getMessageBody];
    url_ = nil;
    httpConn_ = nil;
    statusMessage_ = nil;
    statusBody_ = nil;
  }
  @catch (JavaLangThrowable *ignore) {
  }
}

- (void)copyAllFieldsTo:(RAREHTTPException *)other {
  [super copyAllFieldsTo:other];
  other->cleanedUp_ = cleanedUp_;
  other->httpConn_ = httpConn_;
  other->statusBody_ = statusBody_;
  other->statusCode_ = statusCode_;
  other->statusMessage_ = statusMessage_;
  other->url_ = url_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "geConnection", NULL, "LJavaNetHttpURLConnection", 0x1, NULL },
    { "getMessageBody", NULL, "LNSString", 0x1, NULL },
    { "getMessage", NULL, "LNSString", 0x1, NULL },
    { "getStatus", NULL, "LNSString", 0x1, NULL },
    { "getStatusEx", NULL, "LNSString", 0x1, NULL },
    { "dealloc", NULL, "V", 0x4, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "statusBody_", NULL, 0x0, "LNSString" },
    { "statusCode_", NULL, 0x0, "I" },
    { "cleanedUp_", NULL, 0x0, "Z" },
    { "statusMessage_", NULL, 0x0, "LNSString" },
    { "httpConn_", NULL, 0x0, "LJavaNetHttpURLConnection" },
    { "url_", NULL, 0x0, "LNSString" },
  };
  static J2ObjcClassInfo _RAREHTTPException = { "HTTPException", "com.appnativa.rare.net", NULL, 0x1, 6, methods, 6, fields, 0, NULL};
  return &_RAREHTTPException;
}

@end
