//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc/testing/mockito/build_result/java/org/mockito/listeners/MethodInvocationReport.java
//
//  Created by tball on 11/23/13.
//

#ifndef _OrgMockitoListenersMethodInvocationReport_H_
#define _OrgMockitoListenersMethodInvocationReport_H_

@class JavaLangThrowable;
@protocol OrgMockitoInvocationDescribedInvocation;

#import "JreEmulation.h"

@protocol OrgMockitoListenersMethodInvocationReport < NSObject, JavaObject >
- (id<OrgMockitoInvocationDescribedInvocation>)getInvocation;
- (id)getReturnedValue;
- (JavaLangThrowable *)getThrowable;
- (BOOL)threwException;
- (NSString *)getLocationOfStubbing;
@end

#endif // _OrgMockitoListenersMethodInvocationReport_H_
