//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/apple-android-htmllabel/org/ccil/cowan/tagsoup/HTMLSchema.java
//
//  Created by decoteaud on 3/11/16.
//

#ifndef _RAREHTMLSchema_H_
#define _RAREHTMLSchema_H_

#import "JreEmulation.h"
#include "org/ccil/cowan/tagsoup/HTMLModels.h"
#include "org/ccil/cowan/tagsoup/Schema.h"

@interface RAREHTMLSchema : RARESchema < RAREHTMLModels > {
}

- (id)init;
@end

typedef RAREHTMLSchema OrgCcilCowanTagsoupHTMLSchema;

#endif // _RAREHTMLSchema_H_
