//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../util/src-apple-porting/com/appnativa/util/io/BufferedReaderEx.java
//
//  Created by decoteaud on 12/8/15.
//

#ifndef _RAREUTBufferedReaderEx_H_
#define _RAREUTBufferedReaderEx_H_

@class JavaIoReader;

#import "JreEmulation.h"
#include "java/io/BufferedReader.h"

@interface RAREUTBufferedReaderEx : JavaIoBufferedReader {
}

- (id)initWithJavaIoReader:(JavaIoReader *)inArg;
- (id)initWithJavaIoReader:(JavaIoReader *)inArg
                   withInt:(int)sz;
@end

typedef RAREUTBufferedReaderEx ComAppnativaUtilIoBufferedReaderEx;

#endif // _RAREUTBufferedReaderEx_H_
