//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/core/com/appnativa/rare/spot/RadioButton.java
//
//  Created by decoteaud on 9/15/15.
//

#include "IOSClass.h"
#include "com/appnativa/rare/spot/RadioButton.h"
#include "com/appnativa/spot/SPOTSequence.h"

@implementation RARESPOTRadioButton

- (id)init {
  return [self initRARESPOTRadioButtonWithBoolean:YES];
}

- (id)initRARESPOTRadioButtonWithBoolean:(BOOL)optional {
  if (self = [super initWithBoolean:optional withBoolean:NO]) {
    [self spot_setElements];
  }
  return self;
}

- (id)initWithBoolean:(BOOL)optional {
  return [self initRARESPOTRadioButtonWithBoolean:optional];
}

- (id)initWithBoolean:(BOOL)optional
          withBoolean:(BOOL)setElements {
  return [super initWithBoolean:optional withBoolean:setElements];
}

- (void)spot_setElements {
  self->attributeSizeHint_ += 1;
  [super spot_setElements];
  [self spot_defineAttributeWithNSString:@"onChange" withNSString:nil];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithBoolean:withBoolean:", NULL, NULL, 0x4, NULL },
    { "spot_setElements", NULL, "V", 0x4, NULL },
  };
  static J2ObjcClassInfo _RARESPOTRadioButton = { "RadioButton", "com.appnativa.rare.spot", NULL, 0x1, 2, methods, 0, NULL, 0, NULL};
  return &_RARESPOTRadioButton;
}

@end
