//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc/testing/mockito/build_result/java/org/mockito/internal/verification/checkers/MissingInvocationChecker.java
//
//  Created by tball on 11/23/13.
//

#ifndef _OrgMockitoInternalVerificationCheckersMissingInvocationChecker_H_
#define _OrgMockitoInternalVerificationCheckersMissingInvocationChecker_H_

@class OrgMockitoExceptionsReporter;
@class OrgMockitoInternalInvocationInvocationMatcher;
@class OrgMockitoInternalInvocationInvocationsFinder;
@protocol JavaUtilList;

#import "JreEmulation.h"

@interface OrgMockitoInternalVerificationCheckersMissingInvocationChecker : NSObject {
 @public
  OrgMockitoExceptionsReporter *reporter_;
  OrgMockitoInternalInvocationInvocationsFinder *finder_;
}

- (id)init;
- (id)initWithOrgMockitoInternalInvocationInvocationsFinder:(OrgMockitoInternalInvocationInvocationsFinder *)finder
                           withOrgMockitoExceptionsReporter:(OrgMockitoExceptionsReporter *)reporter;
- (void)checkWithJavaUtilList:(id<JavaUtilList>)invocations
withOrgMockitoInternalInvocationInvocationMatcher:(OrgMockitoInternalInvocationInvocationMatcher *)wanted;
- (void)copyAllFieldsTo:(OrgMockitoInternalVerificationCheckersMissingInvocationChecker *)other;
@end

J2OBJC_FIELD_SETTER(OrgMockitoInternalVerificationCheckersMissingInvocationChecker, reporter_, OrgMockitoExceptionsReporter *)
J2OBJC_FIELD_SETTER(OrgMockitoInternalVerificationCheckersMissingInvocationChecker, finder_, OrgMockitoInternalInvocationInvocationsFinder *)

#endif // _OrgMockitoInternalVerificationCheckersMissingInvocationChecker_H_
