//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc/testing/mockito/build_result/java/org/mockito/internal/util/DefaultMockingDetails.java
//
//  Created by tball on 11/23/13.
//

#ifndef _OrgMockitoInternalUtilDefaultMockingDetails_H_
#define _OrgMockitoInternalUtilDefaultMockingDetails_H_

@class OrgMockitoInternalUtilMockUtil;

#import "JreEmulation.h"
#include "org/mockito/MockingDetails.h"

@interface OrgMockitoInternalUtilDefaultMockingDetails : NSObject < OrgMockitoMockingDetails > {
 @public
  id toInspect_;
  OrgMockitoInternalUtilMockUtil *delegate_;
}

- (id)initWithId:(id)toInspect
withOrgMockitoInternalUtilMockUtil:(OrgMockitoInternalUtilMockUtil *)delegate;
- (BOOL)isMock;
- (BOOL)isSpy;
- (void)copyAllFieldsTo:(OrgMockitoInternalUtilDefaultMockingDetails *)other;
@end

J2OBJC_FIELD_SETTER(OrgMockitoInternalUtilDefaultMockingDetails, toInspect_, id)
J2OBJC_FIELD_SETTER(OrgMockitoInternalUtilDefaultMockingDetails, delegate_, OrgMockitoInternalUtilMockUtil *)

#endif // _OrgMockitoInternalUtilDefaultMockingDetails_H_
