//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/core/com/appnativa/rare/util/JSONHelper.java
//
//  Created by decoteaud on 7/29/15.
//

#ifndef _RAREJSONHelper_H_
#define _RAREJSONHelper_H_

@class IOSCharArray;
@class RAREUTCharArray;

#import "JreEmulation.h"
#include "java/io/Writer.h"
#include "java/lang/ThreadLocal.h"

@interface RAREJSONHelper : NSObject {
}

+ (IOSCharArray *)hex;
+ (void)setHex:(IOSCharArray *)hex;
+ (JavaLangThreadLocal *)perThreadCABuffer;
+ (void)setPerThreadCABuffer:(JavaLangThreadLocal *)perThreadCABuffer;
- (id)init;
+ (JavaIoWriter *)getWiterWithJavaIoWriter:(JavaIoWriter *)w;
+ (void)encodeWithNSString:(NSString *)pString
          withJavaIoWriter:(JavaIoWriter *)buffer;
+ (void)encodeWithCharArray:(IOSCharArray *)a
                    withInt:(int)pos
                    withInt:(int)len
           withJavaIoWriter:(JavaIoWriter *)buffer
                withBoolean:(BOOL)quote;
+ (void)unicodeWithChar:(unichar)c
       withJavaIoWriter:(JavaIoWriter *)buffer;
@end

typedef RAREJSONHelper ComAppnativaRareUtilJSONHelper;

@interface RAREJSONHelper_JSONStringWriter : JavaIoWriter {
 @public
  JavaIoWriter *writer_;
}

- (id)initWithJavaIoWriter:(JavaIoWriter *)writer;
- (void)writeWithCharArray:(IOSCharArray *)cbuf
                   withInt:(int)off
                   withInt:(int)len;
- (void)flush;
- (void)close;
- (void)copyAllFieldsTo:(RAREJSONHelper_JSONStringWriter *)other;
@end

J2OBJC_FIELD_SETTER(RAREJSONHelper_JSONStringWriter, writer_, JavaIoWriter *)

@interface RAREJSONHelper_$1 : JavaLangThreadLocal {
}

- (RAREUTCharArray *)initialValue OBJC_METHOD_FAMILY_NONE;
- (id)init;
@end

#endif // _RAREJSONHelper_H_
