//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/core/com/appnativa/rare/net/ScriptURLConnection.java
//
//  Created by decoteaud on 7/29/15.
//

#ifndef _RAREScriptURLConnection_H_
#define _RAREScriptURLConnection_H_

@class IOSClass;
@class JavaIoInputStream;
@class JavaIoReader;
@class JavaNetURL;
@class JavaUtilEventObject;
@protocol RAREiWidget;

#import "JreEmulation.h"
#include "com/appnativa/rare/net/iURLConnection.h"
#include "java/net/URLConnection.h"

@interface RAREScriptURLConnection : JavaNetURLConnection < RAREiURLConnection > {
 @public
  NSString *defaultCharset_;
  id<RAREiWidget> contextWidget_;
  JavaUtilEventObject *eventObject_;
  NSString *mimeType_;
  int readTimeout_ScriptURLConnection_;
  id returnValue_;
  NSString *scriptCode_;
  id scriptObjectCode_;
}

- (id)initWithJavaNetURL:(JavaNetURL *)url;
- (id)initWithRAREiWidget:(id<RAREiWidget>)context
           withJavaNetURL:(JavaNetURL *)url
             withNSString:(NSString *)code
             withNSString:(NSString *)mime;
- (void)close;
- (void)connect;
+ (JavaNetURL *)createURLWithRAREiWidget:(id<RAREiWidget>)context
                            withNSString:(NSString *)code
                            withNSString:(NSString *)mimeType;
- (void)disconnect;
- (void)dispose;
- (BOOL)exist;
- (void)open;
- (void)setCharsetWithNSString:(NSString *)cs;
- (void)setDefaultCharsetWithNSString:(NSString *)charset;
- (void)setHeaderFieldWithNSString:(NSString *)name
                      withNSString:(NSString *)value;
- (void)setReadTimeoutWithInt:(int)readTimeout;
- (NSString *)getCharset;
- (id)getConnectionObject;
- (IOSClass *)getConnectionObjectClass;
- (id)getContent;
- (NSString *)getContentAsString;
- (NSString *)getContentType;
- (NSString *)getHeaderFieldWithNSString:(NSString *)name;
- (JavaIoInputStream *)getInputStream;
- (int)getReadTimeout;
- (JavaIoReader *)getReader;
- (int)getResponseCode;
- (id)getContentEx;
- (void)copyAllFieldsTo:(RAREScriptURLConnection *)other;
@end

J2OBJC_FIELD_SETTER(RAREScriptURLConnection, defaultCharset_, NSString *)
J2OBJC_FIELD_SETTER(RAREScriptURLConnection, contextWidget_, id<RAREiWidget>)
J2OBJC_FIELD_SETTER(RAREScriptURLConnection, eventObject_, JavaUtilEventObject *)
J2OBJC_FIELD_SETTER(RAREScriptURLConnection, mimeType_, NSString *)
J2OBJC_FIELD_SETTER(RAREScriptURLConnection, returnValue_, id)
J2OBJC_FIELD_SETTER(RAREScriptURLConnection, scriptCode_, NSString *)
J2OBJC_FIELD_SETTER(RAREScriptURLConnection, scriptObjectCode_, id)

typedef RAREScriptURLConnection ComAppnativaRareNetScriptURLConnection;

#endif // _RAREScriptURLConnection_H_
