//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/apple-android-htmllabel/android/text/style/SuperscriptSpan.java
//
//  Created by decoteaud on 9/15/15.
//

#ifndef _RARESuperscriptSpan_H_
#define _RARESuperscriptSpan_H_

#import "JreEmulation.h"
#include "android/text/style/MetricAffectingSpan.h"

@interface RARESuperscriptSpan : RAREMetricAffectingSpan {
}

- (id)init;
- (int)getSpanTypeId;
@end

typedef RARESuperscriptSpan AndroidTextStyleSuperscriptSpan;

#endif // _RARESuperscriptSpan_H_
