//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/apple-android-htmllabel/android/text/NoCopySpan.java
//
//  Created by decoteaud on 5/11/15.
//

#include "android/text/NoCopySpan.h"


@interface AndroidTextNoCopySpan : NSObject
@end

@implementation AndroidTextNoCopySpan

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcClassInfo _AndroidTextNoCopySpan = { "NoCopySpan", "android.text", NULL, 0x201, 0, NULL, 0, NULL, 0, NULL};
  return &_AndroidTextNoCopySpan;
}

@end
@implementation AndroidTextNoCopySpan_Concrete

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcClassInfo _AndroidTextNoCopySpan_Concrete = { "Concrete", "android.text", "NoCopySpan", 0x9, 0, NULL, 0, NULL, 0, NULL};
  return &_AndroidTextNoCopySpan_Concrete;
}

@end
