//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/core/com/appnativa/rare/ui/effects/aPullBackAnimation.java
//
//  Created by decoteaud on 9/15/15.
//

#ifndef _RAREaPullBackAnimation_H_
#define _RAREaPullBackAnimation_H_

@class RARESlideAnimation;
@class RAREUIPoint;
@class RAREiAnimator_DirectionEnum;
@protocol JavaUtilMap;
@protocol RAREiPlatformAnimator;
@protocol RAREiPlatformComponent;

#import "JreEmulation.h"
#include "com/appnativa/rare/ui/effects/aPlatformAnimator.h"

@interface RAREaPullBackAnimation : RAREaPlatformAnimator {
 @public
  RARESlideAnimation *slide_;
  RARESlideAnimation *slideBack_;
  RAREUIPoint *location_;
}

- (id)init;
- (id)initWithBoolean:(BOOL)horizontal;
- (id)initWithBoolean:(BOOL)horizontal
          withBoolean:(BOOL)fromLeftOrTop;
- (void)notifyListenersWithRAREiPlatformAnimator:(id<RAREiPlatformAnimator>)animator
                                     withBoolean:(BOOL)ended;
- (void)animateWithRAREiPlatformComponent:(id<RAREiPlatformComponent>)c
                                   withId:(id)postAnimateAction;
- (void)handlePropertiesWithJavaUtilMap:(id<JavaUtilMap>)map;
- (void)setDirectionWithRAREiAnimator_DirectionEnum:(RAREiAnimator_DirectionEnum *)direction;
- (void)setDurationWithInt:(int)duration;
- (void)setHorizontalWithBoolean:(BOOL)horizontal;
- (void)copyAllFieldsTo:(RAREaPullBackAnimation *)other;
@end

J2OBJC_FIELD_SETTER(RAREaPullBackAnimation, slide_, RARESlideAnimation *)
J2OBJC_FIELD_SETTER(RAREaPullBackAnimation, slideBack_, RARESlideAnimation *)
J2OBJC_FIELD_SETTER(RAREaPullBackAnimation, location_, RAREUIPoint *)

typedef RAREaPullBackAnimation ComAppnativaRareUiEffectsAPullBackAnimation;

#endif // _RAREaPullBackAnimation_H_
