//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc/testing/mockito/build_result/java/org/mockito/invocation/InvocationOnMock.java
//
//  Created by tball on 11/23/13.
//

#ifndef _OrgMockitoInvocationInvocationOnMock_H_
#define _OrgMockitoInvocationInvocationOnMock_H_

@class IOSObjectArray;
@class JavaLangReflectMethod;

#import "JreEmulation.h"
#include "java/io/Serializable.h"

@protocol OrgMockitoInvocationInvocationOnMock < JavaIoSerializable, NSObject, JavaObject >
- (id)getMock;
- (JavaLangReflectMethod *)getMethod;
- (IOSObjectArray *)getArguments;
- (id)callRealMethod;
@end

#endif // _OrgMockitoInvocationInvocationOnMock_H_
