//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../util/src-json/com/appnativa/util/json/JSONException.java
//
//  Created by decoteaud on 12/8/15.
//

#ifndef _RAREUTJSONException_H_
#define _RAREUTJSONException_H_

@class JavaLangThrowable;

#import "JreEmulation.h"
#include "java/lang/RuntimeException.h"

@interface RAREUTJSONException : JavaLangRuntimeException {
 @public
  JavaLangThrowable *cause_;
}

- (id)initWithNSString:(NSString *)message;
- (id)initWithJavaLangThrowable:(JavaLangThrowable *)t;
- (JavaLangThrowable *)getCause;
- (void)copyAllFieldsTo:(RAREUTJSONException *)other;
@end

J2OBJC_FIELD_SETTER(RAREUTJSONException, cause_, JavaLangThrowable *)

typedef RAREUTJSONException ComAppnativaUtilJsonJSONException;

#endif // _RAREUTJSONException_H_
