//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/core/com/appnativa/rare/ui/effects/aPullBackAnimation.java
//
//  Created by decoteaud on 12/8/15.
//

#include "IOSClass.h"
#include "com/appnativa/rare/ui/UIPoint.h"
#include "com/appnativa/rare/ui/effects/SlideAnimation.h"
#include "com/appnativa/rare/ui/effects/aPullBackAnimation.h"
#include "com/appnativa/rare/ui/effects/iAnimator.h"
#include "com/appnativa/rare/ui/effects/iPlatformAnimator.h"
#include "com/appnativa/rare/ui/iPlatformComponent.h"
#include "java/lang/Boolean.h"
#include "java/util/Map.h"

@implementation RAREaPullBackAnimation

- (id)init {
  return [self initRAREaPullBackAnimationWithBoolean:YES withBoolean:YES];
}

- (id)initWithBoolean:(BOOL)horizontal {
  return [self initRAREaPullBackAnimationWithBoolean:horizontal withBoolean:YES];
}

- (id)initRAREaPullBackAnimationWithBoolean:(BOOL)horizontal
                                withBoolean:(BOOL)fromLeftOrTop {
  if (self = [super init]) {
    slide_ = [[RARESlideAnimation alloc] initWithBoolean:horizontal withBoolean:fromLeftOrTop];
    slideBack_ = [[RARESlideAnimation alloc] initWithBoolean:horizontal withBoolean:!fromLeftOrTop];
    [slide_ setDurationWithInt:150];
    [slideBack_ setDurationWithInt:150];
    [slide_ setPercentWithFloat:.25f];
    [slideBack_ setPercentWithFloat:.25f];
    [slide_ setAccelerationWithFloat:.9f];
    [slideBack_ setDecelerationWithFloat:.9f];
    [super setDirectionWithRAREiAnimator_DirectionEnum:fromLeftOrTop ? [RAREiAnimator_DirectionEnum BACKWARD] : [RAREiAnimator_DirectionEnum FORWARD]];
  }
  return self;
}

- (id)initWithBoolean:(BOOL)horizontal
          withBoolean:(BOOL)fromLeftOrTop {
  return [self initRAREaPullBackAnimationWithBoolean:horizontal withBoolean:fromLeftOrTop];
}

- (void)notifyListenersWithRAREiPlatformAnimator:(id<RAREiPlatformAnimator>)animator
                                     withBoolean:(BOOL)ended {
  if (ended && (location_ != nil) && ![location_ isEqual:[((id<RAREiPlatformComponent>) nil_chk(component_)) getLocation]]) {
    [component_ setLocationWithFloat:location_->x_ withFloat:location_->y_];
  }
  [super notifyListenersWithRAREiPlatformAnimator:animator withBoolean:ended];
}

- (void)animateWithRAREiPlatformComponent:(id<RAREiPlatformComponent>)c
                                   withId:(id)postAnimateAction {
  self->postAnimateAction_ = postAnimateAction;
  self->component_ = c;
  location_ = [((id<RAREiPlatformComponent>) nil_chk(c)) getLocation];
  [((RARESlideAnimation *) nil_chk(slide_)) animateWithRAREiPlatformComponent:c withId:nil];
}

- (void)handlePropertiesWithJavaUtilMap:(id<JavaUtilMap>)map {
  [super handlePropertiesWithJavaUtilMap:map];
  if (map == nil) {
    return;
  }
  id o = [((id<JavaUtilMap>) nil_chk(map)) getWithId:@"horizontal"];
  if ([o isKindOfClass:[JavaLangBoolean class]]) {
    [self setHorizontalWithBoolean:[((JavaLangBoolean *) check_class_cast(o, [JavaLangBoolean class])) booleanValue]];
  }
  else if ([o isKindOfClass:[NSString class]]) {
    [self setHorizontalWithBoolean:[@"true" equalsIgnoreCase:(NSString *) check_class_cast(o, [NSString class])]];
  }
}

- (void)setDirectionWithRAREiAnimator_DirectionEnum:(RAREiAnimator_DirectionEnum *)direction {
  [super setDirectionWithRAREiAnimator_DirectionEnum:direction];
  [((RARESlideAnimation *) nil_chk(slide_)) setDirectionWithRAREiAnimator_DirectionEnum:direction];
  [((RARESlideAnimation *) nil_chk(slideBack_)) setDirectionWithRAREiAnimator_DirectionEnum:(direction == [RAREiAnimator_DirectionEnum FORWARD]) ? [RAREiAnimator_DirectionEnum BACKWARD] : [RAREiAnimator_DirectionEnum FORWARD]];
}

- (void)setDurationWithInt:(int)duration {
  [super setDurationWithInt:duration];
  [((RARESlideAnimation *) nil_chk(slide_)) setDurationWithInt:(int) (duration * .75)];
  [((RARESlideAnimation *) nil_chk(slideBack_)) setDurationWithInt:(int) (duration * .25)];
}

- (void)setHorizontalWithBoolean:(BOOL)horizontal {
  [((RARESlideAnimation *) nil_chk(slide_)) setHorizontalWithBoolean:horizontal];
  [((RARESlideAnimation *) nil_chk(slideBack_)) setHorizontalWithBoolean:horizontal];
}

- (void)copyAllFieldsTo:(RAREaPullBackAnimation *)other {
  [super copyAllFieldsTo:other];
  other->location_ = location_;
  other->slide_ = slide_;
  other->slideBack_ = slideBack_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "notifyListenersWithRAREiPlatformAnimator:withBoolean:", NULL, "V", 0x4, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "slide_", NULL, 0x4, "LRARESlideAnimation" },
    { "slideBack_", NULL, 0x4, "LRARESlideAnimation" },
    { "location_", NULL, 0x4, "LRAREUIPoint" },
  };
  static J2ObjcClassInfo _RAREaPullBackAnimation = { "aPullBackAnimation", "com.appnativa.rare.ui.effects", NULL, 0x1, 1, methods, 3, fields, 0, NULL};
  return &_RAREaPullBackAnimation;
}

@end
