//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/AbstractMap.java
//
//  Created by tball on 11/23/13.
//

#ifndef _JavaUtilAbstractMap_H_
#define _JavaUtilAbstractMap_H_

@protocol JavaUtilCollection;
@protocol JavaUtilSet;

#import "JreEmulation.h"
#include "java/io/Serializable.h"
#include "java/util/AbstractCollection.h"
#include "java/util/AbstractSet.h"
#include "java/util/Iterator.h"
#include "java/util/Map.h"

@interface JavaUtilAbstractMap : NSObject < JavaUtilMap > {
 @public
  id<JavaUtilSet> keySet__;
  id<JavaUtilCollection> valuesCollection_;
}

- (id)init;
- (void)clear;
- (BOOL)containsKeyWithId:(id)key;
- (BOOL)containsValueWithId:(id)value;
- (id<JavaUtilSet>)entrySet;
- (BOOL)isEqual:(id)object;
- (id)getWithId:(id)key;
- (NSUInteger)hash;
- (BOOL)isEmpty;
- (id<JavaUtilSet>)keySet;
- (id)putWithId:(id)key
         withId:(id)value;
- (void)putAllWithJavaUtilMap:(id<JavaUtilMap>)map;
- (id)removeWithId:(id)key;
- (int)size;
- (NSString *)description;
- (id<JavaUtilCollection>)values;
- (id)clone;
- (void)copyAllFieldsTo:(JavaUtilAbstractMap *)other;
@end

J2OBJC_FIELD_SETTER(JavaUtilAbstractMap, keySet__, id<JavaUtilSet>)
J2OBJC_FIELD_SETTER(JavaUtilAbstractMap, valuesCollection_, id<JavaUtilCollection>)

#define JavaUtilAbstractMap_SimpleImmutableEntry_serialVersionUID 7138329143949025153

@interface JavaUtilAbstractMap_SimpleImmutableEntry : NSObject < JavaUtilMap_Entry, JavaIoSerializable > {
 @public
  id key_;
  id value_;
}

- (id)initWithId:(id)theKey
          withId:(id)theValue;
- (id)initWithJavaUtilMap_Entry:(id<JavaUtilMap_Entry>)copyFrom;
- (id)getKey;
- (id)getValue;
- (id)setValueWithId:(id)object;
- (BOOL)isEqual:(id)object;
- (NSUInteger)hash;
- (NSString *)description;
- (void)copyAllFieldsTo:(JavaUtilAbstractMap_SimpleImmutableEntry *)other;
@end

J2OBJC_FIELD_SETTER(JavaUtilAbstractMap_SimpleImmutableEntry, key_, id)
J2OBJC_FIELD_SETTER(JavaUtilAbstractMap_SimpleImmutableEntry, value_, id)

#define JavaUtilAbstractMap_SimpleEntry_serialVersionUID -8499721149061103585

@interface JavaUtilAbstractMap_SimpleEntry : NSObject < JavaUtilMap_Entry, JavaIoSerializable > {
 @public
  id key_;
  id value_;
}

- (id)initWithId:(id)theKey
          withId:(id)theValue;
- (id)initWithJavaUtilMap_Entry:(id<JavaUtilMap_Entry>)copyFrom;
- (id)getKey;
- (id)getValue;
- (id)setValueWithId:(id)object;
- (BOOL)isEqual:(id)object;
- (NSUInteger)hash;
- (NSString *)description;
- (void)copyAllFieldsTo:(JavaUtilAbstractMap_SimpleEntry *)other;
@end

J2OBJC_FIELD_SETTER(JavaUtilAbstractMap_SimpleEntry, key_, id)
J2OBJC_FIELD_SETTER(JavaUtilAbstractMap_SimpleEntry, value_, id)

@interface JavaUtilAbstractMap_keySet_AbstractMapKeySet : JavaUtilAbstractSet {
 @public
  __weak JavaUtilAbstractMap *this$0_;
}

- (BOOL)containsWithId:(id)object;
- (int)size;
- (id<JavaUtilIterator>)iterator;
- (id)initWithJavaUtilAbstractMap:(JavaUtilAbstractMap *)outer$;
@end

@interface JavaUtilAbstractMap_keySet_AbstractMapKeySet_$1 : NSObject < JavaUtilIterator > {
 @public
  id<JavaUtilIterator> setIterator_;
}

- (BOOL)hasNext;
- (id)next;
- (void)remove;
- (id)initWithJavaUtilAbstractMap_keySet_AbstractMapKeySet:(JavaUtilAbstractMap_keySet_AbstractMapKeySet *)outer$;
- (void)copyAllFieldsTo:(JavaUtilAbstractMap_keySet_AbstractMapKeySet_$1 *)other;
@end

J2OBJC_FIELD_SETTER(JavaUtilAbstractMap_keySet_AbstractMapKeySet_$1, setIterator_, id<JavaUtilIterator>)

@interface JavaUtilAbstractMap_values_AbstractMapValuesCollection : JavaUtilAbstractCollection {
 @public
  __weak JavaUtilAbstractMap *this$0_;
}

- (int)size;
- (BOOL)containsWithId:(id)object;
- (id<JavaUtilIterator>)iterator;
- (id)initWithJavaUtilAbstractMap:(JavaUtilAbstractMap *)outer$;
@end

@interface JavaUtilAbstractMap_values_AbstractMapValuesCollection_$1 : NSObject < JavaUtilIterator > {
 @public
  id<JavaUtilIterator> setIterator_;
}

- (BOOL)hasNext;
- (id)next;
- (void)remove;
- (id)initWithJavaUtilAbstractMap_values_AbstractMapValuesCollection:(JavaUtilAbstractMap_values_AbstractMapValuesCollection *)outer$;
- (void)copyAllFieldsTo:(JavaUtilAbstractMap_values_AbstractMapValuesCollection_$1 *)other;
@end

J2OBJC_FIELD_SETTER(JavaUtilAbstractMap_values_AbstractMapValuesCollection_$1, setIterator_, id<JavaUtilIterator>)

#endif // _JavaUtilAbstractMap_H_
