//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/Observable.java
//
//  Created by tball on 11/23/13.
//

#ifndef _JavaUtilObservable_H_
#define _JavaUtilObservable_H_

@protocol JavaUtilList;
@protocol JavaUtilObserver;

#import "JreEmulation.h"

@interface JavaUtilObservable : NSObject {
 @public
  id<JavaUtilList> observers_;
  BOOL changed_;
}

- (id)init;
- (void)addObserverWithJavaUtilObserver:(id<JavaUtilObserver>)observer;
- (void)clearChanged;
- (int)countObservers;
- (void)deleteObserverWithJavaUtilObserver:(id<JavaUtilObserver>)observer;
- (void)deleteObservers;
- (BOOL)hasChanged;
- (void)notifyObservers;
- (void)notifyObserversWithId:(id)data;
- (void)setChanged;
- (void)copyAllFieldsTo:(JavaUtilObservable *)other;
@end

J2OBJC_FIELD_SETTER(JavaUtilObservable, observers_, id<JavaUtilList>)

#endif // _JavaUtilObservable_H_
