//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/TooManyListenersException.java
//
//  Created by tball on 11/23/13.
//

#ifndef _JavaUtilTooManyListenersException_H_
#define _JavaUtilTooManyListenersException_H_

#import "JreEmulation.h"
#include "java/lang/Exception.h"

#define JavaUtilTooManyListenersException_serialVersionUID 5074640544770687831

@interface JavaUtilTooManyListenersException : JavaLangException {
}

- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
@end

#endif // _JavaUtilTooManyListenersException_H_
