//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/core/com/appnativa/rare/spot/StackPane.java
//
//  Created by decoteaud on 7/29/15.
//

#ifndef _RARESPOTStackPane_H_
#define _RARESPOTStackPane_H_

@class RARESPOTWidget;
@class SPOTBoolean;
@class SPOTInteger;
@class SPOTPrintableString;
@class SPOTSet;
@protocol iSPOTElement;

#import "JreEmulation.h"
#include "com/appnativa/rare/spot/Viewer.h"

@interface RARESPOTStackPane : RARESPOTViewer {
 @public
  SPOTBoolean *loadOnActivation_;
  SPOTBoolean *reloadOnActivation_;
  SPOTInteger *selectedIndex_;
  SPOTPrintableString *transitionAnimator_;
  SPOTBoolean *actAsFormViewer_;
  SPOTSet *viewers_;
  SPOTSet *viewerURLs_;
}

- (id)init;
- (id)initWithBoolean:(BOOL)optional;
- (id)initWithBoolean:(BOOL)optional
          withBoolean:(BOOL)setElements;
- (void)spot_setElements;
- (SPOTSet *)getViewers;
- (SPOTSet *)getViewersReference;
- (void)setViewersWithISPOTElement:(id<iSPOTElement>)reference;
- (SPOTSet *)getViewerURLs;
- (SPOTSet *)getViewerURLsReference;
- (void)setViewerURLsWithISPOTElement:(id<iSPOTElement>)reference;
- (RARESPOTWidget *)findWidgetWithNSString:(NSString *)name
                               withBoolean:(BOOL)useNameMap;
- (RARESPOTWidget *)findWidgetWithNSString:(NSString *)name;
- (void)copyAllFieldsTo:(RARESPOTStackPane *)other;
@end

J2OBJC_FIELD_SETTER(RARESPOTStackPane, loadOnActivation_, SPOTBoolean *)
J2OBJC_FIELD_SETTER(RARESPOTStackPane, reloadOnActivation_, SPOTBoolean *)
J2OBJC_FIELD_SETTER(RARESPOTStackPane, selectedIndex_, SPOTInteger *)
J2OBJC_FIELD_SETTER(RARESPOTStackPane, transitionAnimator_, SPOTPrintableString *)
J2OBJC_FIELD_SETTER(RARESPOTStackPane, actAsFormViewer_, SPOTBoolean *)
J2OBJC_FIELD_SETTER(RARESPOTStackPane, viewers_, SPOTSet *)
J2OBJC_FIELD_SETTER(RARESPOTStackPane, viewerURLs_, SPOTSet *)

typedef RARESPOTStackPane ComAppnativaRareSpotStackPane;

#endif // _RARESPOTStackPane_H_
