//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/core/com/appnativa/rare/CallbackFunctionCallback.java
//
//  Created by decoteaud on 9/15/15.
//

#include "com/appnativa/rare/CallbackFunctionCallback.h"
#include "com/appnativa/rare/Platform.h"
#include "com/appnativa/rare/iFunctionCallback.h"

@implementation RARECallbackFunctionCallback

- (id)initWithRAREiFunctionCallback:(id<RAREiFunctionCallback>)cb
                        withBoolean:(BOOL)onUIThread {
  if (self = [super init]) {
    self->cb_ = cb;
    self->onUIThread_ = onUIThread;
  }
  return self;
}

- (void)finishedWithBoolean:(BOOL)canceled
                     withId:(id)returnValue {
  if (cb_ == nil) {
    return;
  }
  if (onUIThread_) {
    if (![RAREPlatform isUIThread]) {
      self->canceled_ = canceled;
      self->returnValue_ = returnValue;
      [RAREPlatform invokeLaterWithJavaLangRunnable:self];
      return;
    }
  }
  @try {
    [((id<RAREiFunctionCallback>) nil_chk(cb_)) finishedWithBoolean:canceled withId:returnValue];
  }
  @finally {
    cb_ = nil;
    returnValue = nil;
  }
}

- (void)run {
  [self finishedWithBoolean:canceled_ withId:returnValue_];
}

- (void)copyAllFieldsTo:(RARECallbackFunctionCallback *)other {
  [super copyAllFieldsTo:other];
  other->canceled_ = canceled_;
  other->cb_ = cb_;
  other->onUIThread_ = onUIThread_;
  other->returnValue_ = returnValue_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcFieldInfo fields[] = {
    { "canceled_", NULL, 0x0, "Z" },
    { "cb_", NULL, 0x0, "LRAREiFunctionCallback" },
    { "onUIThread_", NULL, 0x0, "Z" },
    { "returnValue_", NULL, 0x0, "LNSObject" },
  };
  static J2ObjcClassInfo _RARECallbackFunctionCallback = { "CallbackFunctionCallback", "com.appnativa.rare", NULL, 0x1, 0, NULL, 4, fields, 0, NULL};
  return &_RARECallbackFunctionCallback;
}

@end
