//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/core/com/appnativa/rare/CallbackFunctionRunnable.java
//
//  Created by decoteaud on 3/11/16.
//

#include "com/appnativa/rare/CallbackFunctionRunnable.h"
#include "com/appnativa/rare/iFunctionCallback.h"

@implementation RARECallbackFunctionRunnable

- (id)initWithRAREiFunctionCallback:(id<RAREiFunctionCallback>)cb
                        withBoolean:(BOOL)canceled
                             withId:(id)returnValue {
  if (self = [super init]) {
    self->cb_ = cb;
    self->canceled_ = canceled;
    self->returnValue_ = returnValue;
  }
  return self;
}

- (void)run {
  if (cb_ != nil) {
    @try {
      [cb_ finishedWithBoolean:canceled_ withId:returnValue_];
    }
    @finally {
      cb_ = nil;
    }
  }
}

- (void)copyAllFieldsTo:(RARECallbackFunctionRunnable *)other {
  [super copyAllFieldsTo:other];
  other->canceled_ = canceled_;
  other->cb_ = cb_;
  other->returnValue_ = returnValue_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcFieldInfo fields[] = {
    { "canceled_", NULL, 0x0, "Z" },
    { "cb_", NULL, 0x0, "LRAREiFunctionCallback" },
    { "returnValue_", NULL, 0x0, "LNSObject" },
  };
  static J2ObjcClassInfo _RARECallbackFunctionRunnable = { "CallbackFunctionRunnable", "com.appnativa.rare", NULL, 0x1, 0, NULL, 3, fields, 0, NULL};
  return &_RARECallbackFunctionRunnable;
}

@end
