//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Code/Dev/appNativa/source/rareobjc/../rare/core-canvas/com/appnativa/rare/ui/canvas/Image.java
//
//  Created by decoteaud on 7/29/15.
//

#ifndef _RAREImage_H_
#define _RAREImage_H_

@class IOSIntArray;
@class RAREUIImage;
@protocol RAREiWidget;

#import "JreEmulation.h"
#include "com/appnativa/rare/ui/canvas/iContext.h"
#include "com/appnativa/rare/ui/iImageObserver.h"

@interface RAREImage : NSObject < RAREiContext_iImageElement, RAREiImageObserver > {
 @public
  id<RAREiWidget> context_;
  RAREUIImage *image_;
  id onabort_;
  id onerror_;
  id onload_;
  IOSIntArray *pixelData_;
  NSString *src_;
}

- (id)init;
- (id)initWithNSString:(NSString *)src;
- (id)initWithRAREUIImage:(RAREUIImage *)image;
- (id)initWithInt:(int)width
          withInt:(int)height;
- (void)blur;
- (void)createReflectionWithInt:(int)y
                        withInt:(int)height
                      withFloat:(float)opacity
                        withInt:(int)gap;
- (void)imageLoadedWithRAREUIImage:(RAREUIImage *)image;
- (void)setWithInt:(int)index
           withInt:(int)value;
- (void)setContextWithRAREiWidget:(id<RAREiWidget>)context;
- (void)setOnabortWithId:(id)onabort;
- (void)setOnerrorWithId:(id)onerror;
- (void)setOnloadWithId:(id)onload;
- (void)setPixelsWithIntArray:(IOSIntArray *)pixels
                      withInt:(int)x
                      withInt:(int)y
                      withInt:(int)width
                      withInt:(int)height;
- (void)setSrcWithNSString:(NSString *)src;
- (int)getWithInt:(int)index;
- (id<RAREiWidget>)getContext;
- (int)getHeight;
- (RAREUIImage *)getImage;
- (RAREUIImage *)getImageWithInt:(int)x
                         withInt:(int)y
                         withInt:(int)width
                         withInt:(int)height;
- (id)getOnabort;
- (id)getOnerror;
- (id)getOnload;
- (IOSIntArray *)getPixels;
- (IOSIntArray *)getPixelsWithInt:(int)x
                          withInt:(int)y
                          withInt:(int)width
                          withInt:(int)height;
- (NSString *)getSrc;
- (int)getWidth;
- (void)executeEventWithNSString:(NSString *)event
                          withId:(id)code;
- (void)copyAllFieldsTo:(RAREImage *)other;
@end

J2OBJC_FIELD_SETTER(RAREImage, context_, id<RAREiWidget>)
J2OBJC_FIELD_SETTER(RAREImage, image_, RAREUIImage *)
J2OBJC_FIELD_SETTER(RAREImage, onabort_, id)
J2OBJC_FIELD_SETTER(RAREImage, onerror_, id)
J2OBJC_FIELD_SETTER(RAREImage, onload_, id)
J2OBJC_FIELD_SETTER(RAREImage, pixelData_, IOSIntArray *)
J2OBJC_FIELD_SETTER(RAREImage, src_, NSString *)

typedef RAREImage ComAppnativaRareUiCanvasImage;

#endif // _RAREImage_H_
