//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/io/FileOutputStream.java
//
//  Created by tball on 11/23/13.
//

#ifndef _JavaIoFileOutputStream_H_
#define _JavaIoFileOutputStream_H_

@class IOSByteArray;
@class JavaIoFile;
@class JavaIoFileDescriptor;

#import "JreEmulation.h"
#include "java/io/Closeable.h"
#include "java/io/OutputStream.h"

@interface JavaIoFileOutputStream : JavaIoOutputStream < JavaIoCloseable > {
 @public
  JavaIoFileDescriptor *fd_;
}

- (id)initWithJavaIoFile:(JavaIoFile *)file;
- (id)initWithJavaIoFile:(JavaIoFile *)file
             withBoolean:(BOOL)append;
- (long long int)openWithNSString:(NSString *)path
                      withBoolean:(BOOL)append;
- (id)initWithJavaIoFileDescriptor:(JavaIoFileDescriptor *)fd;
- (id)initWithNSString:(NSString *)filename;
- (id)initWithNSString:(NSString *)filename
           withBoolean:(BOOL)append;
- (void)close;
- (void)closeWithLong:(long long int)descriptor;
- (void)dealloc;
- (JavaIoFileDescriptor *)getFD;
- (void)writeWithByteArray:(IOSByteArray *)buffer;
- (void)writeWithByteArray:(IOSByteArray *)buffer
                   withInt:(int)offset
                   withInt:(int)count;
- (int)nativeWriteWithByteArray:(IOSByteArray *)buffer
                        withInt:(int)offset
                        withInt:(int)count;
- (void)writeWithInt:(int)oneByte;
- (void)openCheck;
- (void)copyAllFieldsTo:(JavaIoFileOutputStream *)other;
@end

J2OBJC_FIELD_SETTER(JavaIoFileOutputStream, fd_, JavaIoFileDescriptor *)

#endif // _JavaIoFileOutputStream_H_
