//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/io/PipedReader.java
//
//  Created by tball on 11/23/13.
//

#ifndef _JavaIoPipedReader_H_
#define _JavaIoPipedReader_H_

@class IOSCharArray;
@class JavaIoPipedWriter;
@class JavaLangThread;

#import "JreEmulation.h"
#include "java/io/Reader.h"

#define JavaIoPipedReader_PIPE_SIZE 1024

@interface JavaIoPipedReader : JavaIoReader {
 @public
  JavaLangThread *lastReader_;
  JavaLangThread *lastWriter_;
  BOOL isClosed_;
  IOSCharArray *buffer_;
  int in_;
  int out_;
  BOOL isConnected_;
}

- (id)init;
- (id)initWithJavaIoPipedWriter:(JavaIoPipedWriter *)outArg;
- (id)initWithInt:(int)pipeSize;
- (id)initWithJavaIoPipedWriter:(JavaIoPipedWriter *)outArg
                        withInt:(int)pipeSize;
- (void)close;
- (void)connectWithJavaIoPipedWriter:(JavaIoPipedWriter *)src;
- (void)establishConnection;
- (int)read;
- (int)readWithCharArray:(IOSCharArray *)buffer
                 withInt:(int)offset
                 withInt:(int)count;
- (BOOL)ready;
- (void)receiveWithChar:(unichar)oneChar;
- (void)receiveWithCharArray:(IOSCharArray *)chars
                     withInt:(int)offset
                     withInt:(int)count;
- (void)done;
- (void)copyAllFieldsTo:(JavaIoPipedReader *)other;
@end

J2OBJC_FIELD_SETTER(JavaIoPipedReader, lastReader_, JavaLangThread *)
J2OBJC_FIELD_SETTER(JavaIoPipedReader, lastWriter_, JavaLangThread *)
J2OBJC_FIELD_SETTER(JavaIoPipedReader, buffer_, IOSCharArray *)

#endif // _JavaIoPipedReader_H_
